#!/usr/bin/env python3
# gen-verdict.py <journal.jsonl> <wave> -> writes c<PR>w<wave>.md per PR from the review-wave journal
import json, sys, re, os
journal, wave = sys.argv[1], sys.argv[2]
S = os.path.dirname(os.path.abspath(journal)) if len(sys.argv) < 4 else sys.argv[3]
out_dir = sys.argv[3] if len(sys.argv) > 3 else os.path.dirname(os.path.abspath(__file__))
rows = [json.loads(l) for l in open(journal) if l.strip()]
res = {}
labels = {r["key"]: r.get("label", "") for r in rows if r.get("type") == "started" and r.get("key")}
for r in rows:
    lab = r.get("label") or labels.get(r.get("key", ""), "") or (r.get("opts") or {}).get("label") or ""
    val = r.get("result") if "result" in r else r.get("value")
    m = re.match(r"(review|refute):#(\d+) r(\d+)", lab)
    if not m or val is None: continue
    kind, pr, rnd = m.group(1), m.group(2), m.group(3)
    res.setdefault(pr, {"round": rnd})[kind] = val
def esc(s): return str(s).replace("@claude", "@ claude")
for pr, d in res.items():
    rv, rf = d.get("review"), d.get("refute")
    if not rv: continue
    verdict = rv["verdict"]
    upheld = None if rf is None else rf.get("upheld")
    if rf is not None and upheld is False and rf.get("counter_verdict"):
        final = rf["counter_verdict"]
    else:
        final = verdict
    lines = []
    lines.append(f"## Review round {d['round']} — verdict: **{final}** (head `{rv['head_verified']}`)\n")
    ref = ("adversarial refuter: **upheld**" if upheld else ("adversarial refuter: **REFUTED** (counter-verdict " + rf.get("counter_verdict","?") + ")" if rf is not None else "no Opus refute by routing"))
    lines.append(f"Reviewed by the cloud lane (Sonnet review + Opus refute, DR-047 review tiers). Independent reviewer: **{verdict}**; {ref}.")
    lines.append(f"Tier: {rv['tier']}. Gating: {esc(rv['gating'])} merge-tree vs Alpha: {'clean' if rv['merge_tree_clean'] else 'CONFLICT'}; unresolved threads: {rv['threads_unresolved']}; body truthful: {rv['body_truthful']}.\n")
    lines.append(f"**Reviewer's summary:** {esc(rv['summary'])}\n")
    lines.append(f"**Prior round:** {esc(rv['prior_round_addressed'])}\n")
    if rv["findings"]:
        lines.append("**Findings:**")
        for f in rv["findings"]:
            lines.append(f"- **{f['severity']}** `{f['file']}` — {esc(f['claim'])}\n  Evidence: {esc(f['evidence'])}")
        lines.append("")
    lines.append("**Verified by running (reviewer):**")
    for c in rv["commands_run"][:12]:
        lines.append(f"- `{esc(c['cmd'])}` → exit {c['exit']}: {esc(c['excerpt'])[:300]}")
    if rf is not None:
        lines.append(f"\n**Refuter's summary:** {esc(rf['summary'])}")
        if rf.get("counter_findings"):
            lines.append("\n**Refuter's counter-findings:**")
            for f in rf["counter_findings"]:
                lines.append(f"- **{f['severity']}** `{f['file']}` — {esc(f['claim'])}\n  Evidence: {esc(f['evidence'])}")
        lines.append("\n**Verified by running (refuter):**")
        for c in rf["commands_run"][:10]:
            lines.append(f"- `{esc(c['cmd'])}` → exit {c['exit']}: {esc(c['excerpt'])[:300]}")
        if rf.get("blocked"): lines.append(f"\nRefuter BLOCKED: {esc(rf.get('blocked_reason',''))}")
    if rv.get("blocked"): lines.append(f"\nReviewer BLOCKED: {esc(rv.get('blocked_reason',''))}")
    if final == "ship":
        lines.append("\n**Next:** the cloud lane lands this under DR-037 (merge SignalGrid_Alpha in, regenerate, preflight + breadth on the merged head, push, wait for the gating check, merge). After this verdict, do not push to this branch; LOW/INFO items go to a follow-up PR.")
    elif final == "fix-needed":
        lines.append("\n**Next:** fix on this same branch (the fix commit plus, if mainline moved, a merge of origin/SignalGrid_Alpha), refresh the PR body for the new head with preflight and breadth quoted, then reply here with the new head.")
    else:
        lines.append("\n**Next:** owner-decision — the cloud lane keeps it mergeable; the owner merges or declines.")
    lines.append("\n---\n_Generated by [Claude Code](https://claude.ai/code)_")
    p = os.path.join(out_dir, f"c{pr}w{wave}.md")
    open(p, "w").write("\n".join(lines) + "\n"); print("wrote", p, final, "upheld=", upheld)
