// Remediation-allow resolution — the guard that lives AROUND the engine.
//
// WHY THIS FILE EXISTS, and why it is not a two-line edit to the engine.
//
// `decisionEngine.ts`'s remediation branch adds `allow` when a `remediation.verified`
// signal arrives together with an authenticated identity and a posture reading. The
// BASE-TRUST allow one block below it additionally requires `outcomes.size === 0` —
// nothing else may have been found — and the remediation branch does not. The
// allow-suppression that follows removes `allow` only for `restrict` / `deny` /
// `step_up` and for custody failures, so a finding that produces none of those
// (`api.integration_failed` → INTEGRATION_ROUTE_DEGRADED, `device.low_battery` →
// BATTERY_WORKFLOW_RISK, `device.health_degraded` → OPERATIONAL_HEALTH_DEGRADED)
// rides along and the decision still carries `allow`. The IDENTICAL evidence WITHOUT
// the remediation record yields no allow, because there the `outcomes.size === 0`
// guard applies. A remediation record therefore BUYS an allow that base trust would
// have refused, which is the inverse of what remediation evidence means.
//
// The engine is not fixed in place because
// `native/ios/EnterpriseShell/Services/DecisionEngine.swift` is a byte-faithful port
// of it (CLAUDE.md golden rule 1, held by `scripts/check-decision-port-parity.mjs`).
// Editing the TS body would silently diverge the phone from the fabric. So the fix
// goes AROUND the engine, on both sides — this module, and its Swift twin when the
// Mac lane ports it against `native/shared/remediation-allow-vectors.json`.
//
// ── THE RULE, stated once ────────────────────────────────────────────────────
//
//   An `allow` the engine offered stands only if the remediation evidence is
//   VERIFIED and nothing else was found alongside it: a remediation that is
//   recorded-but-not-verified, recorded with a failure, absent where one was
//   required, stale beyond the caller's declared evidence window, or illegible
//   never yields `allow`; any other finding present in the same decision never
//   yields `allow`; the withheld allow drops to the NEXT-STRICTER outcome with a
//   named reason code; an unknown or illegible remediation state raises the
//   outcome and never lowers it; and this wrapper never moves the engine's own
//   outcome in the permissive direction.
//
// GATED here, because each is unambiguous: the remediation state a record resolves
// to, whether `allow` survives, and the reason code. NOT decided here, and said out
// loud so a green run is not read as broader than it is: how far a deficient
// remediation should escalate BEYOND withholding the grant. This module withholds by
// exactly one step and stops. Escalating a failed remediation to `restrict` would be
// this wrapper inventing a policy the engine never stated, and inventing policy
// outside the ported body is the same divergence in the other direction.
//
// Deterministic and clock-free: the reference instant is a REQUIRED argument. There
// is no `Date.now()` anywhere in this file and there must not be one — the Swift twin
// has to reproduce every vector exactly.

import type { DecisionOutcome, SignalGridDecision } from "./types";

/** The four outcomes a host app can actually meet (CLAUDE.md embedded-UX law). */
export const HOST_OUTCOMES = ["allow", "step_up", "restrict", "deny"] as const;
export type HostOutcome = (typeof HOST_OUTCOMES)[number];

/**
 * The remediation states this wrapper distinguishes.
 *
 * Declared as a runtime array with the type DERIVED from it, not the other way
 * around: a hand-written union beside a hand-written list is two lists that must
 * agree, and the proof sweeps this array to prove every member is exercised. A
 * state added here with no vector fails the proof rather than passing unnoticed.
 */
export const REMEDIATION_STATES = [
  "verified",
  "recorded_unverified",
  "recorded_failed",
  "stale",
  "absent",
  "illegible",
] as const;
export type RemediationState = (typeof REMEDIATION_STATES)[number];

/**
 * Every reason code this wrapper can emit. Same derivation discipline as above.
 *
 * SCOPE NOTE, stated rather than implied: these are the WRAPPER's codes, a
 * simulator/iOS surface, never the launch `/v1` vocabulary. Since #405 the reason-
 * code catalog (`docs/REASON_CODES.md`, generated by `scripts/gen-reason-codes.mjs`)
 * DERIVES this declared array and lists all eight under the simulator vocabulary; a
 * drift guard fails generation if any reason-code literal here is not in this array.
 * They are pinned in three places that must agree: this array, the shared vector
 * file the Swift twin binds to, and the byte-equality catalog gate.
 */
export const REMEDIATION_ALLOW_REASONS = [
  /** Evidence is verified and fresh; the engine's outcome stands unchanged. */
  "REMEDIATION_VERIFIED",
  /** No remediation was required and none was offered; nothing to withhold. */
  "REMEDIATION_NOT_REQUIRED",
  /** A record exists and has not been verified. Recorded is not verified. */
  "REMEDIATION_RECORDED_NOT_VERIFIED",
  /** A record exists and its verification FAILED. */
  "REMEDIATION_VERIFICATION_FAILED",
  /** Verified, but older than the caller's declared evidence window. */
  "REMEDIATION_EVIDENCE_STALE",
  /** The decision required a remediation and no record arrived. */
  "REMEDIATION_ABSENT_WHERE_REQUIRED",
  /** The record, its instant, or the freshness bound could not be read at all. */
  "REMEDIATION_STATE_ILLEGIBLE",
  /** Evidence was fine; the engine reported another finding in the same decision. */
  "ALLOW_WITHHELD_CONCURRENT_FAILURE",
] as const;
export type RemediationAllowReason = (typeof REMEDIATION_ALLOW_REASONS)[number];

/**
 * A remediation record as it arrives from a ticketing / MDM boundary.
 *
 * Every field is `unknown` ON PURPOSE. This record crosses a system boundary, so
 * "the type says it is a string" is a claim about the compiler, not about the byte
 * that arrived. Typing it `string` would make the ILLEGIBLE branch unreachable in
 * TypeScript and reachable in production, which is the fail-open this module exists
 * to close.
 */
export interface RemediationRecord {
  id?: unknown;
  status?: unknown;
  verifiedAt?: unknown;
}

export interface RemediationAllowInput {
  /** The engine's own decision. Read, never mutated, never re-derived. */
  decision: Pick<SignalGridDecision, "outcomes">;
  /** The remediation record, or its absence. */
  record?: RemediationRecord | null;
  /** Reference instant, ISO-8601. REQUIRED: this module reads no clock. */
  asOf: string;
  /** How old verified evidence may be, in ms. Non-finite/negative reads ILLEGIBLE. */
  evidenceMaxAgeMs: number;
  /**
   * A requirement the CALLER knows about that the decision does not express.
   * It can only ADD a requirement — it can never remove one the engine implied.
   */
  policyRequiresRemediation?: boolean;
}

export interface RemediationAllowOutcome {
  /** What the engine offered, projected onto the host's four outcomes. */
  engineOutcome: HostOutcome;
  /** What the host sees. Never less strict than `engineOutcome`. */
  hostOutcome: HostOutcome;
  remediationState: RemediationState;
  remediationRequired: boolean;
  /**
   * This wrapper's verdict ON THE REMEDIATION AXIS — not, in general, the cause of
   * `hostOutcome`. It says so precisely because the loose reading is wrong in a case
   * that occurs constantly: an engine `restrict` with verified evidence passes
   * through and reports `REMEDIATION_VERIFIED`, which did not cause the restrict.
   * The engine's outcome stands on the engine's own reason codes, which this module
   * neither reads nor restates; this code is only ever the answer to "what did the
   * remediation evidence say". When `allowWithheld` is true — and only then — it is
   * also the cause of the change.
   */
  reasonCode: RemediationAllowReason;
  /** Every cause found, in the order they were evaluated. */
  reasonCodes: RemediationAllowReason[];
  /** True when the engine offered `allow` and this wrapper took it away. */
  allowWithheld: boolean;
  /** Engine outcomes that are findings rather than grants. Derived, see below. */
  concurrentFindings: DecisionOutcome[];
}

/**
 * Outcomes that are NOT a finding: the grant itself, the audit record every decision
 * carries, and the acknowledgement that remediation evidence was seen. Anything else
 * in a decision is something the engine found. Three names, listed once; the finding
 * set is the COMPLEMENT, so a new DecisionOutcome counts as a finding by default
 * rather than being silently ignored.
 */
const NON_FINDING_OUTCOMES: ReadonlySet<DecisionOutcome> = new Set<DecisionOutcome>([
  "allow",
  "record_audit",
  "verify_remediation",
]);

/** Strictness ladder. Higher is stricter. */
const STRICTNESS: Record<HostOutcome, number> = {
  allow: 0,
  step_up: 1,
  restrict: 2,
  deny: 3,
};

export function strictnessOf(outcome: HostOutcome): number {
  return STRICTNESS[outcome];
}

/** The next-stricter outcome. `deny` is the ceiling and stays there. */
export function nextStricter(outcome: HostOutcome): HostOutcome {
  const rank = STRICTNESS[outcome];
  return HOST_OUTCOMES.find((candidate) => STRICTNESS[candidate] === rank + 1) ?? "deny";
}

/**
 * Project the engine's outcome SET onto the one outcome a host meets.
 *
 * Fail-closed and non-inventive: `allow` is returned only when the engine actually
 * said `allow`. A decision with findings but no explicit gate outcome — e.g.
 * `[alert_operator, route_to_owner, record_audit]` — is NOT a grant, so it projects
 * to the least-strict NON-grant, `step_up`. The alternative (projecting it to
 * `allow`) would have this wrapper manufacture a grant nobody issued.
 */
export function projectEngineOutcome(outcomes: readonly DecisionOutcome[]): HostOutcome {
  if (outcomes.includes("deny")) return "deny";
  if (outcomes.includes("restrict")) return "restrict";
  if (outcomes.includes("step_up")) return "step_up";
  if (outcomes.includes("allow")) return "allow";
  return "step_up";
}

/**
 * Was a remediation required? DERIVED from the decision the engine already made —
 * `request_remediation` (one was asked for) or `verify_remediation` (one was
 * acknowledged) — union'd with any requirement the caller states. Union only: the
 * caller can add a requirement, never cancel one.
 */
export function remediationRequiredBy(
  outcomes: readonly DecisionOutcome[],
  policyRequiresRemediation?: boolean,
): boolean {
  return (
    outcomes.includes("request_remediation") ||
    outcomes.includes("verify_remediation") ||
    policyRequiresRemediation === true
  );
}

/** Status vocabularies. An unrecognised word is ILLEGIBLE, never a pass. */
const STATUS_VERIFIED = new Set(["verified", "verification_passed", "closed_verified"]);
const STATUS_FAILED = new Set(["failed", "verification_failed", "rejected", "reopened"]);
const STATUS_UNVERIFIED = new Set([
  "requested",
  "recorded",
  "pending",
  "in_progress",
  "submitted",
  "unverified",
  "awaiting_verification",
]);

/**
 * Parse an ISO-8601 instant. An unreadable instant returns `undefined`, and every
 * caller below treats `undefined` as ILLEGIBLE — never as fresh, never as absent.
 * `Number.isFinite` is checked here, at the parse, so no comparison downstream can
 * ever be made against NaN (which compares false to everything and would answer
 * "not stale" for the one value nothing could read).
 */
// An instant is read ONLY as an explicitly-zoned RFC3339 date-time. Date.parse
// interprets a zoneless date-time ("2026-06-09T13:55:00") in the HOST's LOCAL
// time and a bare date ("2026-06-09") as UTC — the first is machine- and
// clock-dependent, which golden rule 2 forbids in a decision path, and neither
// has a counterpart in the Swift twin's ISO8601 parser
// (native/ios/EnterpriseShell/Services/RemediationAllow.swift). Requiring a Z or a
// numeric offset makes the parse deterministic and keeps the two ports in lockstep;
// anything else reads as illegible (raises, never lowers). The regex fixes the
// SHAPE; Date.parse still validates the VALUE (a bogus offset is NaN -> undefined).
const RFC3339_ZONED = /^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(?:\.\d+)?(?:Z|[+-]\d{2}:\d{2})$/;
function instantMs(value: unknown): number | undefined {
  if (typeof value !== "string") return undefined;
  if (!RFC3339_ZONED.test(value)) return undefined;
  const parsed = Date.parse(value);
  return Number.isFinite(parsed) ? parsed : undefined;
}

/**
 * Resolve a raw record to one of the six states.
 *
 * Order matters and is fail-closed throughout: illegibility is decided BEFORE
 * freshness, and freshness before the record is allowed to count as verified.
 */
export function classifyRemediation(
  record: RemediationRecord | null | undefined,
  options: { asOf: string; evidenceMaxAgeMs: number },
): RemediationState {
  if (record === null || record === undefined) return "absent";

  // A record with no readable identity cannot be reconciled with anything later.
  if (typeof record.id !== "string" || record.id.trim() === "") return "illegible";
  if (typeof record.status !== "string" || record.status.trim() === "") return "illegible";

  const status = record.status.trim().toLowerCase();
  if (STATUS_FAILED.has(status)) return "recorded_failed";
  if (STATUS_UNVERIFIED.has(status)) return "recorded_unverified";
  // Unknown vocabulary. It is NOT "probably fine": a word this build has never seen
  // is exactly the input a fail-open is made of.
  if (!STATUS_VERIFIED.has(status)) return "illegible";

  // From here the record CLAIMS verification, so the instants have to hold up.
  const referenceMs = instantMs(options.asOf);
  const verifiedMs = instantMs(record.verifiedAt);
  if (referenceMs === undefined || verifiedMs === undefined) return "illegible";
  if (!Number.isFinite(options.evidenceMaxAgeMs) || options.evidenceMaxAgeMs < 0) {
    // The window itself is unreadable, so "within the window" is unanswerable.
    return "illegible";
  }

  // freshness: local-by-design — this package is dependency-free so the Swift twin can be a byte-faithful port; skew tolerance is ZERO because both instants belong to one evaluation record and there is no second clock to disagree, and a verification dated after the reference is not evidence of freshness, so it RAISES to illegible rather than reading fresh
  if (verifiedMs > referenceMs) return "illegible";
  // freshness: local-by-design — same body as the line above; the bound is the caller's declared evidence window, and evidence older than it is STALE rather than fresh
  if (referenceMs - verifiedMs > options.evidenceMaxAgeMs) return "stale";

  return "verified";
}

/** The reason code a deficient state carries. Total over `RemediationState`. */
const REASON_FOR_STATE: Record<RemediationState, RemediationAllowReason> = {
  verified: "REMEDIATION_VERIFIED",
  recorded_unverified: "REMEDIATION_RECORDED_NOT_VERIFIED",
  recorded_failed: "REMEDIATION_VERIFICATION_FAILED",
  stale: "REMEDIATION_EVIDENCE_STALE",
  absent: "REMEDIATION_ABSENT_WHERE_REQUIRED",
  illegible: "REMEDIATION_STATE_ILLEGIBLE",
};

/**
 * The outcome the host sees.
 *
 * See THE RULE at the top of this file. In code:
 *
 *   1. project the engine's outcome set onto the host's four outcomes;
 *   2. classify the remediation record;
 *   3. a state other than `verified` is DEFICIENT — except `absent` when nothing
 *      required a remediation, which is an ordinary decision and is left alone;
 *   4. a finding present alongside the grant is DISQUALIFYING, which is the
 *      `outcomes.size === 0` guard the base-trust allow applies and the engine's
 *      remediation branch omits;
 *   5. if the engine offered `allow` and either 3 or 4 holds, withhold it to the
 *      next-stricter outcome; otherwise return the engine's outcome unchanged.
 *
 * Step 5 is the only step that can change an outcome, and it only ever moves in the
 * stricter direction — there is no branch in this function that lowers strictness.
 */
export function resolveRemediationAllow(input: RemediationAllowInput): RemediationAllowOutcome {
  const outcomes = input.decision.outcomes;
  const engineOutcome = projectEngineOutcome(outcomes);
  const remediationRequired = remediationRequiredBy(outcomes, input.policyRequiresRemediation);
  const remediationState = classifyRemediation(input.record, {
    asOf: input.asOf,
    evidenceMaxAgeMs: input.evidenceMaxAgeMs,
  });

  const concurrentFindings = outcomes.filter((outcome) => !NON_FINDING_OUTCOMES.has(outcome));

  // `absent` with nothing requiring a remediation is not a deficiency. This is the
  // ordinary happy path — an identity-and-posture allow with no remediation anywhere
  // near it — and punishing it would make the wrapper fire on correct behaviour.
  const stateDeficient =
    remediationState !== "verified" && !(remediationState === "absent" && !remediationRequired);

  const reasonCodes: RemediationAllowReason[] = [];
  if (stateDeficient) {
    reasonCodes.push(REASON_FOR_STATE[remediationState]);
  } else if (remediationState === "verified") {
    reasonCodes.push("REMEDIATION_VERIFIED");
  } else {
    reasonCodes.push("REMEDIATION_NOT_REQUIRED");
  }
  if (concurrentFindings.length > 0 && outcomes.includes("allow")) {
    reasonCodes.push("ALLOW_WITHHELD_CONCURRENT_FAILURE");
  }

  const mustWithhold = engineOutcome === "allow" && (stateDeficient || concurrentFindings.length > 0);
  const hostOutcome = mustWithhold ? nextStricter(engineOutcome) : engineOutcome;

  // The primary cause names the EVIDENCE when the evidence is at fault, and the
  // concurrent finding only when the evidence was fine. Deterministic, so the Swift
  // twin has one answer to reproduce.
  const reasonCode: RemediationAllowReason = stateDeficient
    ? REASON_FOR_STATE[remediationState]
    : mustWithhold
      ? "ALLOW_WITHHELD_CONCURRENT_FAILURE"
      : reasonCodes[0];

  return {
    engineOutcome,
    hostOutcome,
    remediationState,
    remediationRequired,
    reasonCode,
    reasonCodes,
    allowWithheld: mustWithhold,
    concurrentFindings,
  };
}
