import { Router, type IRouter } from "express";
import { GetIntegrationParams } from "@workspace/api-zod";

const router: IRouter = Router();

const INTEGRATIONS = [
  // ── IGA / Identity Governance & Administration ────────────────────────────
  {
    id: "sailpoint",
    vendor: "SailPoint",
    product: "Identity Security Cloud",
    category: "IGA / IDP",
    signalTypes: ["identity"],
    status: "connected",
    lastSync: new Date(Date.now() - 6_000).toISOString(),
    signalsIngested24h: 8421,
    latencyMs: 112,
    description: "Enterprise IGA — lifecycle management, access certification, and role governance across all enterprise apps.",
  },
  {
    id: "saviynt",
    vendor: "Saviynt",
    product: "Identity Cloud",
    category: "IGA / IDP",
    signalTypes: ["identity"],
    status: "connected",
    lastSync: new Date(Date.now() - 14_000).toISOString(),
    signalsIngested24h: 6203,
    latencyMs: 98,
    description: "Cloud-native IGA and application access governance — provisioning, access requests, and SoD controls.",
  },
  {
    id: "okta",
    vendor: "Okta",
    product: "Workforce Identity + Lifecycle Management",
    category: "IGA / IDP",
    signalTypes: ["identity"],
    status: "connected",
    lastSync: new Date(Date.now() - 8_000).toISOString(),
    signalsIngested24h: 5621,
    latencyMs: 95,
    description: "Identity provider and lifecycle management — SSO, MFA, and automated provisioning for workforce identities.",
  },
  {
    id: "microsoft-entra",
    vendor: "Microsoft",
    product: "Entra ID + Identity Governance",
    category: "IGA / IDP",
    signalTypes: ["identity", "device-posture"],
    status: "connected",
    lastSync: new Date(Date.now() - 12_000).toISOString(),
    signalsIngested24h: 11_847,
    latencyMs: 143,
    description: "Azure AD identity signals — MFA status, conditional access policies, identity risk scores, and device compliance.",
  },
  {
    id: "radiantone",
    vendor: "Radiant Logic",
    product: "RadiantOne Identity Data Platform",
    category: "IGA / IDP",
    signalTypes: ["identity"],
    status: "connected",
    lastSync: new Date(Date.now() - 22_000).toISOString(),
    signalsIngested24h: 3812,
    latencyMs: 167,
    description: "Identity data fabric — unifies identity data from AD, LDAP, databases, and cloud directories into a single identity view.",
  },
  {
    id: "one-identity",
    vendor: "One Identity",
    product: "One Identity Manager",
    category: "IGA / IDP",
    signalTypes: ["identity"],
    status: "degraded",
    lastSync: new Date(Date.now() - 480_000).toISOString(),
    signalsIngested24h: 891,
    latencyMs: 2340,
    errorMessage: "SCIM endpoint returning 503 — retrying with exponential backoff",
    description: "IGA platform — role management, access request workflows, and privileged account governance.",
  },
  {
    id: "manageengine-iga",
    vendor: "ManageEngine",
    product: "ADManager Plus + AD360",
    category: "IGA / IDP",
    signalTypes: ["identity", "operational-signals"],
    status: "connected",
    lastSync: new Date(Date.now() - 35_000).toISOString(),
    signalsIngested24h: 2674,
    latencyMs: 231,
    description: "Active Directory management and identity governance — user lifecycle, group management, and compliance reporting.",
  },
  {
    id: "oracle-idm",
    vendor: "Oracle",
    product: "Oracle Identity Governance",
    category: "IGA / IDP",
    signalTypes: ["identity"],
    status: "not-configured",
    lastSync: null,
    signalsIngested24h: 0,
    latencyMs: 0,
    description: "Oracle IDM — automated provisioning, access certification, and role management for Oracle and non-Oracle applications.",
  },
  {
    id: "netwrix",
    vendor: "Netwrix",
    product: "Netwrix Directory Manager",
    category: "IGA / IDP",
    signalTypes: ["identity", "operational-signals"],
    status: "not-configured",
    lastSync: null,
    signalsIngested24h: 0,
    latencyMs: 0,
    description: "Directory lifecycle management across AD, Entra ID, and Google Workspace — provisioning and access delegation.",
  },
  {
    id: "rsa-governance",
    vendor: "RSA",
    product: "RSA Governance & Lifecycle",
    category: "IGA / IDP",
    signalTypes: ["identity"],
    status: "not-configured",
    lastSync: null,
    signalsIngested24h: 0,
    latencyMs: 0,
    description: "Risk-aware IGA — access request management, policy enforcement, and compliance reporting.",
  },
  {
    id: "ibm-verify",
    vendor: "IBM",
    product: "IBM Security Verify Governance",
    category: "IGA / IDP",
    signalTypes: ["identity"],
    status: "not-configured",
    lastSync: null,
    signalsIngested24h: 0,
    latencyMs: 0,
    description: "IBM IGA — access certification, role management, and SoD enforcement across hybrid cloud environments.",
  },
  {
    id: "pathlock",
    vendor: "Pathlock",
    product: "Pathlock Cloud",
    category: "IGA / IDP",
    signalTypes: ["identity", "operational-signals"],
    status: "not-configured",
    lastSync: null,
    signalsIngested24h: 0,
    latencyMs: 0,
    description: "Fine-grained access governance for SAP, Oracle, and business-critical apps — SoD controls and audit readiness.",
  },

  // ── MDM / UEM ─────────────────────────────────────────────────────────────
  {
    id: "intune",
    vendor: "Microsoft",
    product: "Microsoft Intune",
    category: "MDM / UEM",
    signalTypes: ["device-posture"],
    status: "connected",
    lastSync: new Date(Date.now() - 9_000).toISOString(),
    signalsIngested24h: 4203,
    latencyMs: 187,
    description: "Cloud-based UEM — device compliance, app management, and endpoint protection for Windows, macOS, iOS, and Android.",
  },
  {
    id: "jamf",
    vendor: "Jamf",
    product: "Jamf Pro",
    category: "MDM / UEM",
    signalTypes: ["device-posture"],
    status: "degraded",
    lastSync: new Date(Date.now() - 600_000).toISOString(),
    signalsIngested24h: 341,
    latencyMs: 1840,
    errorMessage: "API rate limit approaching — throttling signal ingestion",
    description: "Apple-focused MDM — device enrollment, configuration profiles, and compliance for Mac, iPhone, and iPad fleets.",
  },
  {
    id: "workspace-one",
    vendor: "Omnissa (VMware)",
    product: "Workspace ONE UEM",
    category: "MDM / UEM",
    signalTypes: ["device-posture", "session-context"],
    status: "connected",
    lastSync: new Date(Date.now() - 30_000).toISOString(),
    signalsIngested24h: 2187,
    latencyMs: 265,
    description: "Unified endpoint management across all device types — compliance enforcement and app delivery for frontline workers.",
  },
  {
    id: "fleet",
    vendor: "Fleet",
    product: "Fleet MDM",
    category: "MDM / UEM",
    signalTypes: ["device-posture"],
    status: "connected",
    lastSync: new Date(Date.now() - 45_000).toISOString(),
    signalsIngested24h: 1842,
    latencyMs: 312,
    description: "Open-source MDM and osquery fleet management — real-time device telemetry and compliance posture.",
  },
  {
    id: "hexnode",
    vendor: "Mitsogo (Hexnode)",
    product: "Hexnode UEM",
    category: "MDM / UEM",
    signalTypes: ["device-posture", "session-context"],
    status: "connected",
    lastSync: new Date(Date.now() - 60_000).toISOString(),
    signalsIngested24h: 892,
    latencyMs: 341,
    description: "Multi-platform UEM with kiosk management — purpose-built for shared and frontline device deployments.",
  },
  {
    id: "tanium",
    vendor: "Tanium",
    product: "Tanium Autonomous IT Platform",
    category: "MDM / UEM",
    signalTypes: ["device-posture", "operational-signals"],
    status: "connected",
    lastSync: new Date(Date.now() - 20_000).toISOString(),
    signalsIngested24h: 672,
    latencyMs: 6100,
    description: "Real-time endpoint visibility and control — sub-15-second device query latency across 100k+ endpoints.",
  },
  {
    id: "ivanti",
    vendor: "Ivanti",
    product: "Ivanti Neurons for UEM",
    category: "MDM / UEM",
    signalTypes: ["device-posture"],
    status: "not-configured",
    lastSync: null,
    signalsIngested24h: 0,
    latencyMs: 0,
    description: "AI-powered UEM — self-healing endpoints and automated patch management for enterprise device fleets.",
  },
  {
    id: "maas360",
    vendor: "IBM",
    product: "IBM Security MaaS360",
    category: "MDM / UEM",
    signalTypes: ["device-posture", "identity"],
    status: "not-configured",
    lastSync: null,
    signalsIngested24h: 0,
    latencyMs: 0,
    description: "AI-driven UEM — unified management for endpoints, apps, and content with Watson-powered threat insights.",
  },
  {
    id: "ninjarmm",
    vendor: "NinjaOne",
    product: "NinjaOne RMM",
    category: "MDM / UEM",
    signalTypes: ["device-posture"],
    status: "not-configured",
    lastSync: null,
    signalsIngested24h: 0,
    latencyMs: 0,
    description: "MSP-oriented RMM and endpoint management — patch management, monitoring, and remote control.",
  },
  {
    id: "manageengine-uem",
    vendor: "ManageEngine",
    product: "Endpoint Central",
    category: "MDM / UEM",
    signalTypes: ["device-posture"],
    status: "not-configured",
    lastSync: null,
    signalsIngested24h: 0,
    latencyMs: 0,
    description: "Unified endpoint management and security — patch management, OS deployment, and software distribution.",
  },

  // ── EDR / XDR ─────────────────────────────────────────────────────────────
  {
    id: "crowdstrike",
    vendor: "CrowdStrike",
    product: "Falcon Platform",
    category: "EDR / XDR",
    signalTypes: ["device-posture", "operational-signals"],
    status: "connected",
    lastSync: new Date(Date.now() - 4_000).toISOString(),
    signalsIngested24h: 14_892,
    latencyMs: 68,
    description: "Cloud-native EDR/XDR — real-time threat detection, Zero Trust assessment scores, and device health telemetry.",
  },
  {
    id: "sentinelone",
    vendor: "SentinelOne",
    product: "Singularity Platform",
    category: "EDR / XDR",
    signalTypes: ["device-posture", "operational-signals"],
    status: "connected",
    lastSync: new Date(Date.now() - 11_000).toISOString(),
    signalsIngested24h: 9341,
    latencyMs: 84,
    description: "AI-powered EDR/XDR — autonomous threat response and device risk scoring integrated with the Ranger network discovery.",
  },
  {
    id: "defender",
    vendor: "Microsoft",
    product: "Defender for Endpoint",
    category: "EDR / XDR",
    signalTypes: ["device-posture", "operational-signals"],
    status: "connected",
    lastSync: new Date(Date.now() - 7_000).toISOString(),
    signalsIngested24h: 7234,
    latencyMs: 129,
    description: "Microsoft EDR — device risk scores, security configuration assessment, and threat & vulnerability management.",
  },
  {
    id: "palo-alto-cortex",
    vendor: "Palo Alto Networks",
    product: "Cortex XDR",
    category: "EDR / XDR",
    signalTypes: ["device-posture", "operational-signals"],
    status: "not-configured",
    lastSync: null,
    signalsIngested24h: 0,
    latencyMs: 0,
    description: "Extended detection and response — correlates endpoint, network, and cloud data for unified threat analysis.",
  },

  // ── SIEM / Log Analytics ──────────────────────────────────────────────────
  {
    id: "splunk",
    vendor: "Splunk",
    product: "Splunk Enterprise Security",
    category: "SIEM",
    signalTypes: ["operational-signals", "identity"],
    status: "connected",
    lastSync: new Date(Date.now() - 16_000).toISOString(),
    signalsIngested24h: 3201,
    latencyMs: 298,
    description: "SIEM correlation — enriched security events, user behavior analytics, and operational signal aggregation.",
  },
  {
    id: "sentinel",
    vendor: "Microsoft",
    product: "Microsoft Sentinel",
    category: "SIEM",
    signalTypes: ["operational-signals", "identity"],
    status: "connected",
    lastSync: new Date(Date.now() - 25_000).toISOString(),
    signalsIngested24h: 2847,
    latencyMs: 341,
    description: "Cloud-native SIEM/SOAR — AI-driven threat detection and investigation across Azure and hybrid environments.",
  },
  {
    id: "elastic-siem",
    vendor: "Elastic",
    product: "Elastic SIEM",
    category: "SIEM",
    signalTypes: ["operational-signals"],
    status: "not-configured",
    lastSync: null,
    signalsIngested24h: 0,
    latencyMs: 0,
    description: "Open-source SIEM on the Elastic Stack — real-time threat detection and investigation workflows.",
  },

  // ── ITSM ─────────────────────────────────────────────────────────────────
  {
    id: "servicenow",
    vendor: "ServiceNow",
    product: "ServiceNow ITSM",
    category: "ITSM",
    signalTypes: ["operational-signals"],
    status: "connected",
    lastSync: new Date(Date.now() - 90_000).toISOString(),
    signalsIngested24h: 284,
    latencyMs: 423,
    description: "IT service management — open incident context, change windows, and CMDB device records.",
  },
  {
    id: "jira",
    vendor: "Atlassian",
    product: "Jira Service Management",
    category: "ITSM",
    signalTypes: ["operational-signals"],
    status: "connected",
    lastSync: new Date(Date.now() - 180_000).toISOString(),
    signalsIngested24h: 121,
    latencyMs: 387,
    description: "ITSM and incident management — open ticket context and escalation signals for operational risk assessment.",
  },
];

router.get("/integrations", (_req, res) => {
  res.json({ integrations: INTEGRATIONS });
});

router.get("/integrations/:id", (req, res) => {
  const parsed = GetIntegrationParams.safeParse(req.params);
  if (!parsed.success) {
    res.status(400).json({ error: "validation", message: "Invalid integration ID" });
    return;
  }

  const integration = INTEGRATIONS.find((i) => i.id === parsed.data.id);
  if (!integration) {
    res.status(404).json({ error: "not_found", message: "Integration not found" });
    return;
  }

  res.json(integration);
});

export default router;
