import { Router, type IRouter } from "express";
import { GetIntegrationParams } from "@workspace/api-zod";

const router: IRouter = Router();

const INTEGRATIONS = [
  // ── IGA / Identity Governance & Administration ────────────────────────────
  {
    id: "sailpoint",
    vendor: "SailPoint",
    product: "Identity Security Cloud",
    category: "IGA / IDP",
    signalTypes: ["identity"],
    status: "connected",
    lastSync: new Date(Date.now() - 6_000).toISOString(),
    signalsIngested24h: 8421,
    latencyMs: 112,
    githubUrl: "https://github.com/sailpoint-oss",
    apiDocsUrl: "https://developer.sailpoint.com/docs/api",
    description: "Enterprise IGA — lifecycle management, access certification, and role governance across all enterprise apps. One of the leading Gartner Magic Quadrant Leaders for IGA.",
  },
  {
    id: "saviynt",
    vendor: "Saviynt",
    product: "Identity Cloud",
    category: "IGA / IDP",
    signalTypes: ["identity"],
    status: "connected",
    lastSync: new Date(Date.now() - 14_000).toISOString(),
    signalsIngested24h: 6203,
    latencyMs: 98,
    description: "Cloud-native IGA and application access governance — provisioning, access requests, and SoD controls.",
  },
  {
    id: "okta",
    vendor: "Okta",
    product: "Workforce Identity + Lifecycle Management",
    category: "IGA / IDP",
    signalTypes: ["identity"],
    status: "connected",
    lastSync: new Date(Date.now() - 8_000).toISOString(),
    signalsIngested24h: 5621,
    latencyMs: 95,
    githubUrl: "https://github.com/okta",
    apiDocsUrl: "https://developer.okta.com/docs/api",
    description: "Identity provider and lifecycle management — SSO, MFA, and automated provisioning for workforce identities.",
  },
  {
    id: "microsoft-entra",
    vendor: "Microsoft",
    product: "Entra ID + Identity Governance",
    category: "IGA / IDP",
    signalTypes: ["identity", "device-posture"],
    status: "connected",
    lastSync: new Date(Date.now() - 12_000).toISOString(),
    signalsIngested24h: 11_847,
    latencyMs: 143,
    apiDocsUrl: "https://learn.microsoft.com/en-us/graph/api/overview",
    description: "Azure AD identity signals — MFA status, conditional access policies, identity risk scores, and device compliance. Microsoft Graph API integration.",
  },
  {
    id: "auth0",
    vendor: "Okta",
    product: "Auth0",
    category: "IGA / IDP",
    signalTypes: ["identity"],
    status: "connected",
    lastSync: new Date(Date.now() - 55_000).toISOString(),
    signalsIngested24h: 3102,
    latencyMs: 88,
    githubUrl: "https://github.com/auth0",
    apiDocsUrl: "https://auth0.com/docs/api",
    description: "Developer-focused CIAM platform — authentication, authorization, and user management with extensive SDK ecosystem.",
  },
  {
    id: "keycloak",
    vendor: "Red Hat",
    product: "Keycloak",
    category: "IGA / IDP",
    signalTypes: ["identity"],
    status: "connected",
    lastSync: new Date(Date.now() - 40_000).toISOString(),
    signalsIngested24h: 2841,
    latencyMs: 134,
    githubUrl: "https://github.com/keycloak/keycloak",
    description: "Open-source IAM — SSO, OIDC/SAML federation, user federation, and fine-grained authorization. Self-hosted identity for enterprises requiring data sovereignty.",
  },
  {
    id: "teleport",
    vendor: "Gravitational",
    product: "Teleport",
    category: "IGA / IDP",
    signalTypes: ["identity", "session-context"],
    status: "connected",
    lastSync: new Date(Date.now() - 28_000).toISOString(),
    signalsIngested24h: 1923,
    latencyMs: 76,
    githubUrl: "https://github.com/gravitational/teleport",
    apiDocsUrl: "https://goteleport.com/docs/api/",
    description: "Zero Trust access platform for infrastructure — SSH, Kubernetes, databases, and internal apps with full session recording and audit trail.",
  },
  {
    id: "zitadel",
    vendor: "ZITADEL",
    product: "ZITADEL Cloud",
    category: "IGA / IDP",
    signalTypes: ["identity"],
    status: "not-configured",
    lastSync: null,
    signalsIngested24h: 0,
    latencyMs: 0,
    githubUrl: "https://github.com/zitadel/zitadel",
    description: "Open-source identity infrastructure — multi-tenancy, passwordless auth, and fine-grained permission system built for cloud-native architectures.",
  },
  {
    id: "radiantone",
    vendor: "Radiant Logic",
    product: "RadiantOne Identity Data Platform",
    category: "IGA / IDP",
    signalTypes: ["identity"],
    status: "connected",
    lastSync: new Date(Date.now() - 22_000).toISOString(),
    signalsIngested24h: 3812,
    latencyMs: 167,
    description: "Identity data fabric — unifies identity data from AD, LDAP, databases, and cloud directories into a single identity view.",
  },
  {
    id: "one-identity",
    vendor: "One Identity",
    product: "One Identity Manager",
    category: "IGA / IDP",
    signalTypes: ["identity"],
    status: "degraded",
    lastSync: new Date(Date.now() - 480_000).toISOString(),
    signalsIngested24h: 891,
    latencyMs: 2340,
    errorMessage: "SCIM endpoint returning 503 — retrying with exponential backoff",
    description: "IGA platform — role management, access request workflows, and privileged account governance.",
  },
  {
    id: "manageengine-iga",
    vendor: "ManageEngine",
    product: "ADManager Plus + AD360",
    category: "IGA / IDP",
    signalTypes: ["identity", "operational-signals"],
    status: "connected",
    lastSync: new Date(Date.now() - 35_000).toISOString(),
    signalsIngested24h: 2674,
    latencyMs: 231,
    apiDocsUrl: "https://www.manageengine.com/products/active-directory-manager/help/api-v2/",
    description: "Active Directory management and identity governance — user lifecycle, group management, and compliance reporting.",
  },
  {
    id: "oracle-idm",
    vendor: "Oracle",
    product: "Oracle Identity Governance",
    category: "IGA / IDP",
    signalTypes: ["identity"],
    status: "not-configured",
    lastSync: null,
    signalsIngested24h: 0,
    latencyMs: 0,
    description: "Oracle IDM — automated provisioning, access certification, and role management for Oracle and non-Oracle applications.",
  },
  {
    id: "netwrix",
    vendor: "Netwrix",
    product: "Netwrix Directory Manager",
    category: "IGA / IDP",
    signalTypes: ["identity", "operational-signals"],
    status: "not-configured",
    lastSync: null,
    signalsIngested24h: 0,
    latencyMs: 0,
    description: "Directory lifecycle management across AD, Entra ID, and Google Workspace — provisioning and access delegation.",
  },
  {
    id: "rsa-governance",
    vendor: "RSA",
    product: "RSA Governance & Lifecycle",
    category: "IGA / IDP",
    signalTypes: ["identity"],
    status: "not-configured",
    lastSync: null,
    signalsIngested24h: 0,
    latencyMs: 0,
    description: "Risk-aware IGA — access request management, policy enforcement, and compliance reporting.",
  },
  {
    id: "ibm-verify",
    vendor: "IBM",
    product: "IBM Security Verify Governance",
    category: "IGA / IDP",
    signalTypes: ["identity"],
    status: "not-configured",
    lastSync: null,
    signalsIngested24h: 0,
    latencyMs: 0,
    description: "IBM IGA — access certification, role management, and SoD enforcement across hybrid cloud environments.",
  },
  {
    id: "pathlock",
    vendor: "Pathlock",
    product: "Pathlock Cloud",
    category: "IGA / IDP",
    signalTypes: ["identity", "operational-signals"],
    status: "not-configured",
    lastSync: null,
    signalsIngested24h: 0,
    latencyMs: 0,
    description: "Fine-grained access governance for SAP, Oracle, and business-critical apps — SoD controls and audit readiness.",
  },
  {
    id: "authentik",
    vendor: "Authentik Security",
    product: "Authentik",
    category: "IGA / IDP",
    signalTypes: ["identity"],
    status: "connected",
    lastSync: new Date(Date.now() - 44_000).toISOString(),
    signalsIngested24h: 1782,
    latencyMs: 119,
    githubUrl: "https://github.com/goauthentik/authentik",
    apiDocsUrl: "https://docs.goauthentik.io/developer-docs/api/",
    description: "Open-source identity provider with a focus on flexibility — SSO, MFA, passkeys, LDAP and RADIUS proxy, and flow-based authentication engine. Self-hosted alternative to Okta.",
  },
  {
    id: "privacyidea",
    vendor: "NetKnights",
    product: "privacyIDEA",
    category: "IGA / IDP",
    signalTypes: ["identity"],
    status: "connected",
    lastSync: new Date(Date.now() - 91_000).toISOString(),
    signalsIngested24h: 984,
    latencyMs: 148,
    githubUrl: "https://github.com/privacyidea/privacyidea",
    apiDocsUrl: "https://privacyidea.readthedocs.io/en/latest/",
    description: "Open-source MFA and authentication server — TOTP, HOTP, FIDO2 WebAuthn, smart card, and hardware token management with RADIUS and LDAP integration for enterprise MFA enforcement.",
  },
  {
    id: "imprivata",
    vendor: "Imprivata",
    product: "Imprivata OneSign",
    category: "IGA / IDP",
    signalTypes: ["identity", "physical-access"],
    status: "connected",
    lastSync: new Date(Date.now() - 18_000).toISOString(),
    signalsIngested24h: 4102,
    latencyMs: 109,
    apiDocsUrl: "https://www.imprivata.com/platform/api-integrations",
    description: "Healthcare-focused SSO and authentication for shared workstations — tap-and-go badge login, virtual desktop, and physical/digital access convergence for clinical workflows.",
  },

  // ── MDM / UEM ─────────────────────────────────────────────────────────────
  {
    id: "intune",
    vendor: "Microsoft",
    product: "Microsoft Intune",
    category: "MDM / UEM",
    signalTypes: ["device-posture"],
    status: "connected",
    lastSync: new Date(Date.now() - 9_000).toISOString(),
    signalsIngested24h: 4203,
    latencyMs: 187,
    apiDocsUrl: "https://learn.microsoft.com/en-us/graph/api/resources/intune-graph-overview",
    description: "Cloud-based UEM — device compliance, app management, and endpoint protection for Windows, macOS, iOS, and Android via Microsoft Graph API.",
  },
  {
    id: "jamf",
    vendor: "Jamf",
    product: "Jamf Pro",
    category: "MDM / UEM",
    signalTypes: ["device-posture"],
    status: "degraded",
    lastSync: new Date(Date.now() - 600_000).toISOString(),
    signalsIngested24h: 341,
    latencyMs: 1840,
    errorMessage: "API rate limit approaching — throttling signal ingestion",
    apiDocsUrl: "https://developer.jamf.com/jamf-pro/docs",
    description: "Apple-focused MDM — device enrollment, configuration profiles, and compliance for Mac, iPhone, and iPad fleets.",
  },
  {
    id: "kandji",
    vendor: "Kandji",
    product: "Kandji Device Management",
    category: "MDM / UEM",
    signalTypes: ["device-posture"],
    status: "connected",
    lastSync: new Date(Date.now() - 32_000).toISOString(),
    signalsIngested24h: 1847,
    latencyMs: 142,
    apiDocsUrl: "https://api.kandji.io",
    description: "Modern Apple MDM with one-click compliance blueprints — automated remediation, Liftoff zero-touch deployment, and real-time device health monitoring.",
  },
  {
    id: "workspace-one",
    vendor: "Omnissa (VMware)",
    product: "Workspace ONE UEM",
    category: "MDM / UEM",
    signalTypes: ["device-posture", "session-context"],
    status: "connected",
    lastSync: new Date(Date.now() - 30_000).toISOString(),
    signalsIngested24h: 2187,
    latencyMs: 265,
    apiDocsUrl: "https://developer.omnissa.com/apis/workspace-one-uem",
    description: "Unified endpoint management across all device types — compliance enforcement and app delivery for frontline workers.",
  },
  {
    id: "fleet",
    vendor: "FleetDM",
    product: "Fleet MDM",
    category: "MDM / UEM",
    signalTypes: ["device-posture"],
    status: "connected",
    lastSync: new Date(Date.now() - 45_000).toISOString(),
    signalsIngested24h: 1842,
    latencyMs: 312,
    githubUrl: "https://github.com/fleetdm/fleet",
    description: "Open-source MDM and osquery fleet management — GitOps-driven endpoint configuration, real-time device telemetry, and compliance posture for macOS, Windows, Linux, iOS, and Android.",
  },
  {
    id: "hexnode",
    vendor: "Mitsogo (Hexnode)",
    product: "Hexnode UEM",
    category: "MDM / UEM",
    signalTypes: ["device-posture", "session-context"],
    status: "connected",
    lastSync: new Date(Date.now() - 60_000).toISOString(),
    signalsIngested24h: 892,
    latencyMs: 341,
    apiDocsUrl: "https://www.hexnode.com/mobile-device-management/help/hexnode-api/",
    description: "Multi-platform UEM with kiosk management — purpose-built for shared and frontline device deployments.",
  },
  {
    id: "tanium",
    vendor: "Tanium",
    product: "Tanium Autonomous IT Platform",
    category: "MDM / UEM",
    signalTypes: ["device-posture", "operational-signals"],
    status: "connected",
    lastSync: new Date(Date.now() - 20_000).toISOString(),
    signalsIngested24h: 672,
    latencyMs: 61,
    description: "Real-time endpoint visibility and control — sub-15-second device query latency across 100k+ endpoints via linear-chain architecture.",
  },
  {
    id: "kolide",
    vendor: "Kolide",
    product: "Kolide Device Trust",
    category: "MDM / UEM",
    signalTypes: ["device-posture"],
    status: "connected",
    lastSync: new Date(Date.now() - 50_000).toISOString(),
    signalsIngested24h: 1203,
    latencyMs: 198,
    githubUrl: "https://github.com/kolide/launcher",
    description: "Honest security tool — osquery-powered device trust with user-facing transparency. Blocks SSO access when devices fall out of compliance.",
  },
  {
    id: "santa",
    vendor: "Google",
    product: "Santa (macOS)",
    category: "MDM / UEM",
    signalTypes: ["device-posture"],
    status: "connected",
    lastSync: new Date(Date.now() - 75_000).toISOString(),
    signalsIngested24h: 847,
    latencyMs: 89,
    githubUrl: "https://github.com/google/santa",
    description: "Google's open-source macOS binary authorization system — allowlist/denylist enforcement with centralized sync server for enterprise fleets.",
  },
  {
    id: "osquery",
    vendor: "Meta (OpenSource)",
    product: "osquery",
    category: "MDM / UEM",
    signalTypes: ["device-posture", "operational-signals"],
    status: "connected",
    lastSync: new Date(Date.now() - 15_000).toISOString(),
    signalsIngested24h: 3412,
    latencyMs: 44,
    githubUrl: "https://github.com/osquery/osquery",
    description: "SQL-powered endpoint telemetry engine — query any device attribute (processes, network, files, hardware) using standard SQL across your entire fleet.",
  },
  {
    id: "ivanti",
    vendor: "Ivanti",
    product: "Ivanti Neurons for UEM",
    category: "MDM / UEM",
    signalTypes: ["device-posture"],
    status: "not-configured",
    lastSync: null,
    signalsIngested24h: 0,
    latencyMs: 0,
    description: "AI-powered UEM — self-healing endpoints and automated patch management for enterprise device fleets.",
  },
  {
    id: "maas360",
    vendor: "IBM",
    product: "IBM Security MaaS360",
    category: "MDM / UEM",
    signalTypes: ["device-posture", "identity"],
    status: "not-configured",
    lastSync: null,
    signalsIngested24h: 0,
    latencyMs: 0,
    apiDocsUrl: "https://developer.ibm.com/apis/catalog/maas360--ibm-maas360-apis",
    description: "AI-driven UEM — unified management for endpoints, apps, and content with Watson-powered threat insights.",
  },
  {
    id: "manageengine-uem",
    vendor: "ManageEngine",
    product: "Endpoint Central",
    category: "MDM / UEM",
    signalTypes: ["device-posture"],
    status: "not-configured",
    lastSync: null,
    signalsIngested24h: 0,
    latencyMs: 0,
    description: "Unified endpoint management and security — patch management, OS deployment, and software distribution.",
  },
  {
    id: "mosyle",
    vendor: "Mosyle",
    product: "Mosyle Business + Mosyle Authority",
    category: "MDM / UEM",
    signalTypes: ["device-posture"],
    status: "not-configured",
    lastSync: null,
    signalsIngested24h: 0,
    latencyMs: 0,
    apiDocsUrl: "https://mosyle.com/developers",
    description: "Apple-only MDM for education and business — zero-touch enrollment, compliance automation, and security hardening for iPhone, iPad, Mac, and Apple TV fleets.",
  },
  {
    id: "simplemdm",
    vendor: "SimpleMDM",
    product: "SimpleMDM",
    category: "MDM / UEM",
    signalTypes: ["device-posture"],
    status: "not-configured",
    lastSync: null,
    signalsIngested24h: 0,
    latencyMs: 0,
    apiDocsUrl: "https://simplemdm.com/docs/api/",
    description: "Apple MDM with a developer-friendly REST API — device enrollment, compliance reporting, app deployment, and configuration profile management for Mac and iOS fleets.",
  },
  {
    id: "addigy",
    vendor: "Addigy",
    product: "Addigy Mac MDM",
    category: "MDM / UEM",
    signalTypes: ["device-posture"],
    status: "not-configured",
    lastSync: null,
    signalsIngested24h: 0,
    latencyMs: 0,
    apiDocsUrl: "https://addigy.com/developers/",
    description: "macOS-focused MDM with real-time device monitoring — policy enforcement, compliance checks, and automated remediation for Apple-centric enterprise environments.",
  },

  // ── Rugged Android / Zebra / Enterprise Mobility ─────────────────────────
  {
    id: "zebra-stagenow",
    vendor: "Zebra Technologies",
    product: "StageNow / OEMConfig",
    category: "MDM / UEM",
    signalTypes: ["device-posture"],
    status: "connected",
    lastSync: new Date(Date.now() - 28_000).toISOString(),
    signalsIngested24h: 3412,
    latencyMs: 88,
    githubUrl: "https://github.com/ZebraDevs",
    apiDocsUrl: "https://techdocs.zebra.com/stagenow/",
    description: "Zebra enterprise device staging and OEMConfig MDM — StageNow provisions Zebra TC-series, MC-series, EC-series, and WT-series rugged Android devices at scale. OEMConfig exposes 500+ Zebra-specific settings (DataWedge profiles, FIPS mode, scanner lockdown) through any Android Enterprise MDM. Provides device health, OS version, and posture signals for warehouse, healthcare, and manufacturing environments.",
  },
  {
    id: "zebra-dna-cloud",
    vendor: "Zebra Technologies",
    product: "Zebra DNA Cloud",
    category: "MDM / UEM",
    signalTypes: ["device-posture", "operational-signals"],
    status: "connected",
    lastSync: new Date(Date.now() - 41_000).toISOString(),
    signalsIngested24h: 2871,
    latencyMs: 112,
    githubUrl: "https://github.com/ZebraDevs",
    apiDocsUrl: "https://techdocs.zebra.com/dna/cloud/",
    description: "Zebra connected intelligence platform — DNA Cloud REST API provides real-time device telemetry (battery state, scanner health, Wi-Fi signal, crash analytics, and app performance) for the entire Zebra device fleet. Device intelligence signals feed directly into SignalGrid's operational risk decisions for shared frontline deployments.",
  },
  {
    id: "zebra-lifeguard",
    vendor: "Zebra Technologies",
    product: "Zebra LifeGuard Analytics",
    category: "MDM / UEM",
    signalTypes: ["device-posture"],
    status: "connected",
    lastSync: new Date(Date.now() - 67_000).toISOString(),
    signalsIngested24h: 1203,
    latencyMs: 143,
    apiDocsUrl: "https://techdocs.zebra.com/lifeguard/",
    description: "OS security lifecycle management for Zebra Android devices — LifeGuard Analytics API surfaces patch compliance scores, OS update status, CVE exposure counts, and end-of-support timelines for all Zebra device models. Patch compliance failures and unmitigated CVE findings are surfaced as device-posture risk signals.",
  },
  {
    id: "zebra-datawedge",
    vendor: "Zebra Technologies",
    product: "Zebra DataWedge",
    category: "MDM / UEM",
    signalTypes: ["device-posture", "session-context"],
    status: "connected",
    lastSync: new Date(Date.now() - 19_000).toISOString(),
    signalsIngested24h: 8934,
    latencyMs: 61,
    apiDocsUrl: "https://techdocs.zebra.com/datawedge/",
    description: "Zebra barcode scanner data capture middleware — DataWedge Intent API delivers scan events (barcode type, data, scanner ID, timestamp) to SignalGrid in real time. Badge barcode scans, medication barcode scans, and asset scan events serve as session context signals for custody verification and workflow authorization.", // deferred family — fixture catalog data, not Limited GA capability
  },
  {
    id: "soti-mobicontrol",
    vendor: "SOTI",
    product: "SOTI MobiControl",
    category: "MDM / UEM",
    signalTypes: ["device-posture"],
    status: "not-configured",
    lastSync: null,
    signalsIngested24h: 0,
    latencyMs: 0,
    apiDocsUrl: "https://www.soti.net/products/sotioneplatform/mobicontrol/",
    description: "Enterprise MDM purpose-built for rugged devices — SOTI MobiControl REST API surfaces device compliance state, location tracking, remote lock/wipe status, and app management signals for Zebra, Honeywell, Datalogic, and Panasonic rugged device fleets.",
  },
  {
    id: "42gears-suremdm",
    vendor: "42Gears",
    product: "42Gears SureMDM",
    category: "MDM / UEM",
    signalTypes: ["device-posture"],
    status: "not-configured",
    lastSync: null,
    signalsIngested24h: 0,
    latencyMs: 0,
    githubUrl: "https://github.com/42gears",
    apiDocsUrl: "https://www.42gears.com/products/suremdm/",
    description: "Android and Windows enterprise device management for rugged and kiosk deployments — SureMDM REST API provides device health, geo-fence compliance, kiosk mode enforcement state, and application compliance signals for mixed-OS frontline device fleets.",
  },
  {
    id: "honeywell-mobility",
    vendor: "Honeywell",
    product: "Honeywell Mobility Edge (CT60/CN80/CK65)",
    category: "MDM / UEM",
    signalTypes: ["device-posture"],
    status: "not-configured",
    lastSync: null,
    signalsIngested24h: 0,
    latencyMs: 0,
    apiDocsUrl: "https://sps.honeywell.com/us/en/products/productivity/mobile-computers",
    description: "Honeywell rugged Android mobile computers — CT60/CN80/CK65 Mobility Edge platform device telemetry integrates with Android Enterprise MDM APIs. Device health, scanner state, and battery/environmental condition signals are surfaced for warehouse, distribution center, and clinical logistics environments.",
  },
  {
    id: "datalogic",
    vendor: "Datalogic",
    product: "Datalogic Memor / Falcon X4",
    category: "MDM / UEM",
    signalTypes: ["device-posture", "session-context"],
    status: "not-configured",
    lastSync: null,
    signalsIngested24h: 0,
    latencyMs: 0,
    apiDocsUrl: "https://www.datalogic.com/eng/products/mobile-computers.html",
    description: "Datalogic rugged industrial scanners and mobile computers — Memor 20 and Falcon X4 device health, scan event telemetry, and Android Enterprise compliance state for manufacturing, logistics, and retail warehouse environments.",
  },
  {
    id: "panasonic-toughbook",
    vendor: "Panasonic",
    product: "Panasonic Toughbook",
    category: "MDM / UEM",
    signalTypes: ["device-posture"],
    status: "not-configured",
    lastSync: null,
    signalsIngested24h: 0,
    latencyMs: 0,
    apiDocsUrl: "https://panasonic.net/cns/sav/toughbook/",
    description: "Panasonic ruggedized Windows and Android enterprise devices — Toughbook CF and FZ series device health API surfaces OS compliance, TPM attestation state, fingerprint reader availability, and environmental sensor readings for military, public safety, and field service deployments.",
  },

  // ── EDR / XDR ─────────────────────────────────────────────────────────────
  {
    id: "crowdstrike",
    vendor: "CrowdStrike",
    product: "Falcon Platform",
    category: "EDR / XDR",
    signalTypes: ["device-posture", "operational-signals"],
    status: "connected",
    lastSync: new Date(Date.now() - 4_000).toISOString(),
    signalsIngested24h: 14_892,
    latencyMs: 68,
    apiDocsUrl: "https://developer.crowdstrike.com/crowdstrike/docs",
    description: "Cloud-native EDR/XDR — real-time threat detection, Zero Trust Assessment scores, and device health telemetry via Falcon APIs.",
  },
  {
    id: "sentinelone",
    vendor: "SentinelOne",
    product: "Singularity Platform",
    category: "EDR / XDR",
    signalTypes: ["device-posture", "operational-signals"],
    status: "connected",
    lastSync: new Date(Date.now() - 11_000).toISOString(),
    signalsIngested24h: 9341,
    latencyMs: 84,
    apiDocsUrl: "https://developer.sentinelone.com/",
    description: "AI-powered EDR/XDR — autonomous threat response and device risk scoring integrated with Ranger network discovery.",
  },
  {
    id: "defender",
    vendor: "Microsoft",
    product: "Defender for Endpoint",
    category: "EDR / XDR",
    signalTypes: ["device-posture", "operational-signals"],
    status: "connected",
    lastSync: new Date(Date.now() - 7_000).toISOString(),
    signalsIngested24h: 7234,
    latencyMs: 129,
    description: "Microsoft EDR — device risk scores, security configuration assessment, and threat & vulnerability management via Microsoft Graph Security API.",
  },
  {
    id: "wazuh",
    vendor: "Wazuh",
    product: "Wazuh SIEM + EDR",
    category: "EDR / XDR",
    signalTypes: ["device-posture", "operational-signals"],
    status: "connected",
    lastSync: new Date(Date.now() - 38_000).toISOString(),
    signalsIngested24h: 5102,
    latencyMs: 201,
    githubUrl: "https://github.com/wazuh/wazuh",
    description: "Open-source SIEM/XDR platform — log analysis, intrusion detection, vulnerability detection, and regulatory compliance across hybrid environments.",
  },
  {
    id: "velociraptor",
    vendor: "Rapid7 (OpenSource)",
    product: "Velociraptor",
    category: "EDR / XDR",
    signalTypes: ["device-posture", "operational-signals"],
    status: "connected",
    lastSync: new Date(Date.now() - 62_000).toISOString(),
    signalsIngested24h: 1847,
    latencyMs: 156,
    githubUrl: "https://github.com/Velocidex/velociraptor",
    description: "Advanced digital forensics and incident response platform — real-time endpoint interrogation using VQL (Velociraptor Query Language) for threat hunting at scale.",
  },
  {
    id: "palo-alto-cortex",
    vendor: "Palo Alto Networks",
    product: "Cortex XDR",
    category: "EDR / XDR",
    signalTypes: ["device-posture", "operational-signals"],
    status: "not-configured",
    lastSync: null,
    signalsIngested24h: 0,
    latencyMs: 0,
    githubUrl: "https://github.com/PaloAltoNetworks",
    description: "Extended detection and response — correlates endpoint, network, and cloud data for unified threat analysis.",
  },
  {
    id: "security-onion",
    vendor: "Security Onion Solutions",
    product: "Security Onion",
    category: "EDR / XDR",
    signalTypes: ["network-posture", "operational-signals"],
    status: "not-configured",
    lastSync: null,
    signalsIngested24h: 0,
    latencyMs: 0,
    githubUrl: "https://github.com/Security-Onion-Solutions/securityonion",
    description: "Open-source threat hunting and network security monitoring platform — integrates Zeek, Suricata, Elasticsearch, and Kibana for NSM at scale.",
  },
  {
    id: "sophos",
    vendor: "Sophos",
    product: "Sophos Central",
    category: "EDR / XDR",
    signalTypes: ["device-posture", "operational-signals"],
    status: "not-configured",
    lastSync: null,
    signalsIngested24h: 0,
    latencyMs: 0,
    apiDocsUrl: "https://developer.sophos.com/",
    description: "Synchronized security platform — endpoint, firewall, email, and mobile protection with Security Heartbeat that shares health state across devices for adaptive trust enforcement.",
  },
  {
    id: "carbon-black",
    vendor: "Broadcom (VMware)",
    product: "Carbon Black EDR + App Control",
    category: "EDR / XDR",
    signalTypes: ["device-posture", "operational-signals"],
    status: "not-configured",
    lastSync: null,
    signalsIngested24h: 0,
    latencyMs: 0,
    apiDocsUrl: "https://developer.carbonblack.com/",
    description: "Endpoint detection and response with application allowlisting — continuous recording of all endpoint activity with Carbon Black Cloud REST API for device risk and behavioral threat signals.",
  },
  {
    id: "trend-micro",
    vendor: "Trend Micro",
    product: "Vision One XDR",
    category: "EDR / XDR",
    signalTypes: ["device-posture", "operational-signals"],
    status: "not-configured",
    lastSync: null,
    signalsIngested24h: 0,
    latencyMs: 0,
    apiDocsUrl: "https://automation.trendmicro.com/xdr/home",
    description: "Extended detection and response platform — cross-layer telemetry from endpoint, email, network, and cloud with risk index scoring and automated response playbooks.",
  },
  {
    id: "trellix",
    vendor: "Trellix",
    product: "Trellix XDR Platform",
    category: "EDR / XDR",
    signalTypes: ["device-posture", "operational-signals"],
    status: "not-configured",
    lastSync: null,
    signalsIngested24h: 0,
    latencyMs: 0,
    apiDocsUrl: "https://docs.trellix.com/bundle/trellix-xdr-api/page/index.html",
    description: "Trellix (McAfee Enterprise + FireEye) XDR — unified endpoint, network, and email threat detection with Helix correlation engine for SOC-level signal aggregation.",
  },

  // ── SIEM / Log Analytics ──────────────────────────────────────────────────
  {
    id: "splunk",
    vendor: "Splunk",
    product: "Splunk Enterprise Security",
    category: "SIEM",
    signalTypes: ["operational-signals", "identity"],
    status: "connected",
    lastSync: new Date(Date.now() - 16_000).toISOString(),
    signalsIngested24h: 3201,
    latencyMs: 298,
    apiDocsUrl: "https://dev.splunk.com/enterprise/docs/devtools/restapi/",
    description: "SIEM correlation — enriched security events, user behavior analytics, and operational signal aggregation via REST API and Splunk Web Framework.",
  },
  {
    id: "sentinel",
    vendor: "Microsoft",
    product: "Microsoft Sentinel",
    category: "SIEM",
    signalTypes: ["operational-signals", "identity"],
    status: "connected",
    lastSync: new Date(Date.now() - 25_000).toISOString(),
    signalsIngested24h: 2847,
    latencyMs: 341,
    githubUrl: "https://github.com/Azure/Azure-Sentinel",
    description: "Cloud-native SIEM/SOAR — AI-driven threat detection and investigation. 200+ connectors including Cisco, Fortinet, F5, Symantec, and enterprise security integrations.",
  },
  {
    id: "elastic-siem",
    vendor: "Elastic",
    product: "Elastic Security",
    category: "SIEM",
    signalTypes: ["operational-signals", "network-posture"],
    status: "not-configured",
    lastSync: null,
    signalsIngested24h: 0,
    latencyMs: 0,
    githubUrl: "https://github.com/elastic/security-team",
    apiDocsUrl: "https://www.elastic.co/docs/api/doc/elasticsearch/",
    description: "Open-source SIEM on the Elastic Stack — real-time threat detection, ML anomaly detection, and SOAR-style automated response playbooks.",
  },
  {
    id: "thehive",
    vendor: "StrangeBee",
    product: "TheHive",
    category: "SIEM",
    signalTypes: ["operational-signals"],
    status: "not-configured",
    lastSync: null,
    signalsIngested24h: 0,
    latencyMs: 0,
    githubUrl: "https://github.com/TheHive-Project/TheHive",
    description: "Open-source security incident response platform — case management, alert triage, and MISP threat intelligence integration for SOC teams.",
  },
  {
    id: "google-chronicle",
    vendor: "Google Cloud",
    product: "Google Security Operations (Chronicle)",
    category: "SIEM",
    signalTypes: ["operational-signals", "identity"],
    status: "not-configured",
    lastSync: null,
    signalsIngested24h: 0,
    latencyMs: 0,
    apiDocsUrl: "https://cloud.google.com/chronicle/docs/reference/rest",
    description: "Cloud-scale SIEM built on Google infrastructure — petabyte-scale log ingestion, YARA-L detection rules, and sub-second search across years of security telemetry via Chronicle API.",
  },
  {
    id: "ibm-qradar",
    vendor: "IBM",
    product: "IBM QRadar SIEM",
    category: "SIEM",
    signalTypes: ["operational-signals", "network-posture"],
    status: "not-configured",
    lastSync: null,
    signalsIngested24h: 0,
    latencyMs: 0,
    apiDocsUrl: "https://www.ibm.com/docs/en/qsip/7.5?topic=api-rest",
    description: "Enterprise SIEM with UBA and network anomaly detection — offense correlation, QRadar Use Case Manager, and DSM integration for multi-vendor log normalization.",
  },
  {
    id: "crowdstrike-logscale",
    vendor: "CrowdStrike",
    product: "Falcon LogScale / Next-Gen SIEM",
    category: "SIEM",
    signalTypes: ["operational-signals", "device-posture"],
    status: "not-configured",
    lastSync: null,
    signalsIngested24h: 0,
    latencyMs: 0,
    apiDocsUrl: "https://library.humio.com/falcon-logscale/api-intro.html",
    description: "CrowdStrike's EDR-native SIEM — petabyte-scale log ingestion with sub-second search, Falcon telemetry correlation, and real-time streaming query engine (formerly Humio).",
  },
  {
    id: "sumo-logic",
    vendor: "Sumo Logic",
    product: "Sumo Logic Cloud SIEM",
    category: "SIEM",
    signalTypes: ["operational-signals", "identity"],
    status: "not-configured",
    lastSync: null,
    signalsIngested24h: 0,
    latencyMs: 0,
    apiDocsUrl: "https://api.sumologic.com/docs/",
    description: "Cloud-native log analytics and security — continuous intelligence platform with SIEM, SOAR integration, and machine learning threat detection across cloud-first infrastructures.",
  },
  {
    id: "graylog",
    vendor: "Graylog",
    product: "Graylog Security",
    category: "SIEM",
    signalTypes: ["operational-signals"],
    status: "not-configured",
    lastSync: null,
    signalsIngested24h: 0,
    latencyMs: 0,
    githubUrl: "https://github.com/Graylog2/graylog2-server",
    apiDocsUrl: "https://go2docs.graylog.org/current/setting_up_graylog/rest_api.html",
    description: "Open-source centralized log management with SIEM capabilities — real-time log aggregation, anomaly detection, and alert pipelines for hybrid infrastructure environments.",
  },

  // ── Networking / SDN ──────────────────────────────────────────────────────
  {
    id: "cisco-meraki",
    vendor: "Cisco",
    product: "Meraki Dashboard",
    category: "Networking / SDN",
    signalTypes: ["network-posture", "device-posture"],
    status: "connected",
    lastSync: new Date(Date.now() - 24_000).toISOString(),
    signalsIngested24h: 6821,
    latencyMs: 143,
    apiDocsUrl: "https://developer.cisco.com/meraki/api-v1/",
    description: "Cloud-managed networking platform — network topology, client device context, SSID/VLAN posture, and rogue device detection via Dashboard API.",
  },
  {
    id: "cisco-ise",
    vendor: "Cisco",
    product: "Cisco ISE",
    category: "Networking / SDN",
    signalTypes: ["network-posture", "identity"],
    status: "connected",
    lastSync: new Date(Date.now() - 19_000).toISOString(),
    signalsIngested24h: 4103,
    latencyMs: 289,
    apiDocsUrl: "https://developer.cisco.com/docs/identity-services-engine/",
    description: "Identity Services Engine — policy enforcement point for network access control. Provides device posture, profiling, and 802.1X authentication signals for Zero Trust.",
  },
  {
    id: "cisco-dnac",
    vendor: "Cisco",
    product: "Cisco Catalyst Center (DNAC)",
    category: "Networking / SDN",
    signalTypes: ["network-posture", "operational-signals"],
    status: "connected",
    lastSync: new Date(Date.now() - 90_000).toISOString(),
    signalsIngested24h: 1204,
    latencyMs: 412,
    apiDocsUrl: "https://developer.cisco.com/docs/dna-center/",
    description: "DNA Center network management — network health, device inventory, and topology signals via Intent API for campus Zero Trust enforcement.",
  },
  {
    id: "arista-cloudvision",
    vendor: "Arista",
    product: "CloudVision",
    category: "Networking / SDN",
    signalTypes: ["network-posture", "operational-signals"],
    status: "not-configured",
    lastSync: null,
    signalsIngested24h: 0,
    latencyMs: 0,
    githubUrl: "https://github.com/aristanetworks",
    apiDocsUrl: "https://aristanetworks.github.io/cloudvision-apis/",
    description: "Network-wide telemetry and operations platform — streaming network state, device health, and traffic analytics via CloudVision APIs and EOS SDK.",
  },
  {
    id: "juniper-mist",
    vendor: "Juniper Networks",
    product: "Mist AI",
    category: "Networking / SDN",
    signalTypes: ["network-posture", "device-posture"],
    status: "not-configured",
    lastSync: null,
    signalsIngested24h: 0,
    latencyMs: 0,
    githubUrl: "https://github.com/Juniper",
    description: "AI-driven wireless and wired networking — client experience telemetry, RF optimization, and network anomaly signals via Mist APIs and PyEZ SDK.",
  },
  {
    id: "aruba-central",
    vendor: "HPE Aruba",
    product: "Aruba Central",
    category: "Networking / SDN",
    signalTypes: ["network-posture", "device-posture"],
    status: "not-configured",
    lastSync: null,
    signalsIngested24h: 0,
    latencyMs: 0,
    apiDocsUrl: "https://developer.arubanetworks.com/",
    description: "Cloud-managed networking platform — WLAN, SD-WAN, and switch management with client visibility and network access control integration.",
  },
  {
    id: "netbox",
    vendor: "NetBox Labs",
    product: "NetBox",
    category: "Networking / SDN",
    signalTypes: ["network-posture", "operational-signals"],
    status: "not-configured",
    lastSync: null,
    signalsIngested24h: 0,
    latencyMs: 0,
    githubUrl: "https://github.com/netbox-community/netbox",
    description: "Open-source network source of truth — DCIM/IPAM with comprehensive REST API and GraphQL. Authoritative device, IP, and circuit inventory for network automation.",
  },

  // ── Firewall / SASE ────────────────────────────────────────────────────────
  {
    id: "palo-alto-panos",
    vendor: "Palo Alto Networks",
    product: "PAN-OS + Prisma Cloud",
    category: "Firewall / SASE",
    signalTypes: ["network-posture", "device-posture"],
    status: "connected",
    lastSync: new Date(Date.now() - 31_000).toISOString(),
    signalsIngested24h: 5823,
    latencyMs: 187,
    githubUrl: "https://github.com/PaloAltoNetworks",
    apiDocsUrl: "https://docs.paloaltonetworks.com/pan-os/11-1/pan-os-panorama-api",
    description: "Next-gen firewall and cloud security — traffic policy context, GlobalProtect VPN posture, and Prisma Cloud workload risk signals via PAN-OS REST API and Python SDK.",
  },
  {
    id: "fortinet",
    vendor: "Fortinet",
    product: "FortiGate + FortiSIEM",
    category: "Firewall / SASE",
    signalTypes: ["network-posture", "operational-signals"],
    status: "connected",
    lastSync: new Date(Date.now() - 43_000).toISOString(),
    signalsIngested24h: 4102,
    latencyMs: 231,
    githubUrl: "https://github.com/fortinet",
    apiDocsUrl: "https://fndn.fortinet.net/index.php?/fortiapi/1-fortios/",
    description: "Fortinet Security Fabric — firewall policy context, FortiSIEM event correlation, and FortiNAC network access control signals via REST API.",
  },
  {
    id: "checkpoint",
    vendor: "Check Point",
    product: "Check Point NGFW",
    category: "Firewall / SASE",
    signalTypes: ["network-posture", "operational-signals"],
    status: "not-configured",
    lastSync: null,
    signalsIngested24h: 0,
    latencyMs: 0,
    githubUrl: "https://github.com/CheckPointSW",
    apiDocsUrl: "https://sc1.checkpoint.com/documents/latest/APIs/",
    description: "Check Point next-gen firewall — SmartConsole Management API for policy context, threat intelligence feeds, and network anomaly signals.",
  },
  {
    id: "cortex-xsoar",
    vendor: "Palo Alto Networks",
    product: "Cortex XSOAR",
    category: "Firewall / SASE",
    signalTypes: ["operational-signals"],
    status: "not-configured",
    lastSync: null,
    signalsIngested24h: 0,
    latencyMs: 0,
    githubUrl: "https://github.com/demisto/content",
    description: "SOAR platform — 900+ integration content packs including Cisco, Fortinet, Splunk, and identity providers for automated incident response playbooks.",
  },
  {
    id: "pfsense",
    vendor: "Netgate",
    product: "pfSense / OPNsense",
    category: "Firewall / SASE",
    signalTypes: ["network-posture"],
    status: "not-configured",
    lastSync: null,
    signalsIngested24h: 0,
    latencyMs: 0,
    githubUrl: "https://github.com/pfsense/pfsense",
    description: "Open-source firewall/router platform — pfSense and OPNsense provide REST API and XMLRPC interfaces for firewall rule context and traffic policy signals.",
  },

  // ── Physical Access (PACS) ─────────────────────────────────────────────────
  {
    id: "hid-global",
    vendor: "HID Global",
    product: "HID Origo + SAFE",
    category: "Physical Access (PACS)",
    signalTypes: ["physical-access"],
    status: "connected",
    lastSync: new Date(Date.now() - 10_000).toISOString(),
    signalsIngested24h: 3402,
    latencyMs: 134,
    apiDocsUrl: "https://developer.hidglobal.com/",
    description: "Access control credential and reader ecosystem — badge-in/badge-out events, door access audit trails, and mobile credential status for physical Zero Trust convergence.",
  },
  {
    id: "lenel-s2",
    vendor: "Carrier",
    product: "LenelS2 OnGuard",
    category: "Physical Access (PACS)",
    signalTypes: ["physical-access"],
    status: "connected",
    lastSync: new Date(Date.now() - 22_000).toISOString(),
    signalsIngested24h: 2103,
    latencyMs: 198,
    apiDocsUrl: "https://www.lenel.com/support/developer-programs",
    description: "Enterprise physical access control system — OnGuard API provides real-time door events, cardholder status, and access group membership for identity convergence.",
  },
  {
    id: "genetec",
    vendor: "Genetec",
    product: "Security Center",
    category: "Physical Access (PACS)",
    signalTypes: ["physical-access"],
    status: "connected",
    lastSync: new Date(Date.now() - 35_000).toISOString(),
    signalsIngested24h: 1841,
    latencyMs: 267,
    apiDocsUrl: "https://genetec.com/resources/developer-zone", // deferred family — fixture catalog data, not Limited GA capability
    description: "Unified physical security platform — Security Center SDK provides access control, video surveillance, and ALPR events for unified physical/digital identity posture.",
  },
  {
    id: "gallagher",
    vendor: "Gallagher Security",
    product: "Gallagher Command Centre",
    category: "Physical Access (PACS)",
    signalTypes: ["physical-access"],
    status: "not-configured",
    lastSync: null,
    signalsIngested24h: 0,
    latencyMs: 0,
    apiDocsUrl: "https://gallagher.com/support/developer-tools",
    description: "Enterprise PACS with REST API — access event streaming, cardholder management, and zone occupancy signals for high-security environments.",
  },
  {
    id: "brivo",
    vendor: "Brivo",
    product: "Brivo Access",
    category: "Physical Access (PACS)",
    signalTypes: ["physical-access"],
    status: "not-configured",
    lastSync: null,
    signalsIngested24h: 0,
    latencyMs: 0,
    apiDocsUrl: "https://apidocs.brivo.com/",
    description: "Cloud-based physical access control — Brivo API provides real-time access events, credential management, and video integration for cloud-first deployments.",
  },
  {
    id: "kisi",
    vendor: "Kisi",
    product: "Kisi Access Control",
    category: "Physical Access (PACS)",
    signalTypes: ["physical-access"],
    status: "not-configured",
    lastSync: null,
    signalsIngested24h: 0,
    latencyMs: 0,
    apiDocsUrl: "https://api.kisi.io/docs",
    description: "Modern cloud access control with REST API — mobile credentials, real-time access logs, and lockdown commands for converged physical/digital identity.",
  },
  {
    id: "openpath",
    vendor: "Avigilon Alta",
    product: "Openpath Access Control",
    category: "Physical Access (PACS)",
    signalTypes: ["physical-access"],
    status: "not-configured",
    lastSync: null,
    signalsIngested24h: 0,
    latencyMs: 0,
    apiDocsUrl: "https://openpath.com/resources/openpath-api/",
    description: "Mobile-first enterprise access control — NFC, BLE, and touch-free entry with REST API for real-time access events, remote unlock, and mobile credential provisioning.",
  },
  {
    id: "rfideas",
    vendor: "RF IDeas",
    product: "pcProx Workstation Badge Readers",
    category: "Physical Access (PACS)",
    signalTypes: ["physical-access", "identity"],
    status: "connected",
    lastSync: new Date(Date.now() - 13_000).toISOString(),
    signalsIngested24h: 5841,
    latencyMs: 42,
    apiDocsUrl: "https://rfideas.com/support/developer",
    description: "Badge reader hardware for workstation authentication — tap-to-login and tap-to-lock for shared clinical and frontline devices. SDK integrates with Imprivata, Citrix, and Windows Hello for tap-and-go SSO workflows.",
  },
  {
    id: "suprema",
    vendor: "Suprema",
    product: "BioStar 2",
    category: "Physical Access (PACS)",
    signalTypes: ["physical-access", "identity"],
    status: "not-configured",
    lastSync: null,
    signalsIngested24h: 0,
    latencyMs: 0,
    apiDocsUrl: "https://bs2api.biostar2.com/",
    description: "Biometric access control — fingerprint, face recognition, and mobile credentials with BioStar 2 REST API for real-time biometric authentication events and physical access signals.",
  },
  {
    id: "zkteco",
    vendor: "ZKTeco",
    product: "ZKBioSecurity",
    category: "Physical Access (PACS)",
    signalTypes: ["physical-access", "identity"],
    status: "not-configured",
    lastSync: null,
    signalsIngested24h: 0,
    latencyMs: 0,
    githubUrl: "https://github.com/ZKTeco-Europe",
    description: "Enterprise biometric access and time-attendance platform — fingerprint, face, palm, and card recognition with ZKBioSecurity API for multi-modal identity verification signals.",
  },
  {
    id: "honeywell-prowatch",
    vendor: "Honeywell",
    product: "Pro-Watch Security Suite",
    category: "Physical Access (PACS)",
    signalTypes: ["physical-access"],
    status: "not-configured",
    lastSync: null,
    signalsIngested24h: 0,
    latencyMs: 0,
    apiDocsUrl: "https://buildings.honeywell.com/us/en/products/by-category/security/access-control/pro-watch",
    description: "Enterprise PACS — Pro-Watch SDK provides access event streaming, visitor management integration, and alarm state signals for high-security campus and critical infrastructure deployments.",
  },
  {
    id: "jci-ccure",
    vendor: "Johnson Controls",
    product: "C•CURE 9000",
    category: "Physical Access (PACS)",
    signalTypes: ["physical-access"],
    status: "not-configured",
    lastSync: null,
    signalsIngested24h: 0,
    latencyMs: 0,
    apiDocsUrl: "https://www.johnsoncontrols.com/security/access-control/access-control-software/c-cure-9000",
    description: "Enterprise access and event management system — C•CURE Software House API provides real-time door events, cardholder lifecycle, and access privilege signals across large multi-site deployments.",
  },
  {
    id: "verkada",
    vendor: "Verkada",
    product: "Verkada Access Control",
    category: "Physical Access (PACS)",
    signalTypes: ["physical-access"],
    status: "not-configured",
    lastSync: null,
    signalsIngested24h: 0,
    latencyMs: 0,
    apiDocsUrl: "https://apidocs.verkada.com/",
    description: "Cloud-first physical security platform — unified access control and camera system with REST API for real-time access events, person-of-interest alerts, and video verification signals.",
  },
  {
    id: "salto",
    vendor: "SALTO Systems",
    product: "SALTO KS + SALTO Space",
    category: "Physical Access (PACS)",
    signalTypes: ["physical-access"],
    status: "not-configured",
    lastSync: null,
    signalsIngested24h: 0,
    latencyMs: 0,
    apiDocsUrl: "https://saltoks.com/developers/",
    description: "Electronic lock and cloud access control — SALTO KS API provides keyless entry events, audit trail, and real-time lock state for distributed door environments without traditional wiring.",
  },
  {
    id: "siemens-siveillance",
    vendor: "Siemens",
    product: "Siveillance Access",
    category: "Physical Access (PACS)",
    signalTypes: ["physical-access"],
    status: "not-configured",
    lastSync: null,
    signalsIngested24h: 0,
    latencyMs: 0,
    apiDocsUrl: "https://sie.ag/3M7YhAu",
    description: "Siemens enterprise PACS — Siveillance Access SDK provides badge event streaming, zone occupancy, and integrated video verification for critical infrastructure and large campus environments.",
  },

  // ── Security Keys / FIDO2 ─────────────────────────────────────────────────
  {
    id: "yubico",
    vendor: "Yubico",
    product: "YubiKey + YubiEnterprise",
    category: "Security Keys / FIDO2",
    signalTypes: ["identity", "physical-access"],
    status: "connected",
    lastSync: new Date(Date.now() - 17_000).toISOString(),
    signalsIngested24h: 4203,
    latencyMs: 38,
    githubUrl: "https://github.com/Yubico",
    apiDocsUrl: "https://developers.yubico.com/",
    description: "Hardware security key platform — FIDO2, WebAuthn, PIV smartcard, OTP, OpenPGP, and NFC. YubiEnterprise Subscription API provides fleet management, attestation, and phishing-resistant MFA enforcement signals for Zero Trust.",
  },
  {
    id: "thales-safenet",
    vendor: "Thales",
    product: "SafeNet Trusted Access + FIDO Keys",
    category: "Security Keys / FIDO2",
    signalTypes: ["identity"],
    status: "connected",
    lastSync: new Date(Date.now() - 53_000).toISOString(),
    signalsIngested24h: 1872,
    latencyMs: 141,
    apiDocsUrl: "https://cpl.thalesgroup.com/access-management/safenet-trusted-access",
    description: "Enterprise IAM and hardware authentication — SafeNet FIDO keys, smart cards, and Trusted Access cloud platform with cloud-based access management, policy enforcement, and authentication event signals.",
  },
  {
    id: "feitian",
    vendor: "FEITIAN Technologies",
    product: "FIDO2 Security Keys + BioPass",
    category: "Security Keys / FIDO2",
    signalTypes: ["identity"],
    status: "not-configured",
    lastSync: null,
    signalsIngested24h: 0,
    latencyMs: 0,
    githubUrl: "https://github.com/OpenSK/opensk",
    apiDocsUrl: "https://www.ftsafe.com/developer",
    description: "FIDO2 security keys and biometric authenticators — USB-C/NFC/BLE hardware tokens with fingerprint biometrics (BioPass series) for phishing-resistant enterprise authentication.",
  },
  {
    id: "hid-crescendo",
    vendor: "HID Global",
    product: "Crescendo Smart Cards + FIDO2",
    category: "Security Keys / FIDO2",
    signalTypes: ["identity", "physical-access"],
    status: "connected",
    lastSync: new Date(Date.now() - 26_000).toISOString(),
    signalsIngested24h: 2934,
    latencyMs: 89,
    apiDocsUrl: "https://developer.hidglobal.com/crescendo",
    description: "HID's convergent credential platform — one card for building access and logical authentication. Crescendo integrates FIDO2, PIV/CAC, PACS, and passkeys into a single smart card or mobile credential for physical/digital Zero Trust convergence.",
  },
  {
    id: "solokeys",
    vendor: "SoloKeys",
    product: "Solo 2 FIDO2 Key",
    category: "Security Keys / FIDO2",
    signalTypes: ["identity"],
    status: "not-configured",
    lastSync: null,
    signalsIngested24h: 0,
    latencyMs: 0,
    githubUrl: "https://github.com/solokeys/solo2",
    description: "Open-source FIDO2 hardware security key — fully auditable firmware, NFC + USB-A/C, and support for FIDO2, WebAuthn, and CTAP2. Preferred for security-conscious deployments requiring open-source hardware attestation.",
  },

  // ── Mobile Credentials ─────────────────────────────────────────────────────
  {
    id: "apple-wallet",
    vendor: "Apple",
    product: "Wallet Employee Badge + Corporate Keys",
    category: "Mobile Credentials",
    signalTypes: ["physical-access", "identity"],
    status: "connected",
    lastSync: new Date(Date.now() - 8_000).toISOString(),
    signalsIngested24h: 7412,
    latencyMs: 52,
    apiDocsUrl: "https://developer.apple.com/wallet/",
    description: "Apple Wallet employee badge — NFC tap access with Express Mode (no Face ID required), BLE proximity unlock, and corporate key provisioning. Integrates with HID, Gallagher, Brivo, Genetec, and SwiftConnect for building access signal correlation.", // deferred family — fixture catalog data, not Limited GA capability
  },
  {
    id: "google-wallet",
    vendor: "Google",
    product: "Google Wallet + Android Enterprise Credentials",
    category: "Mobile Credentials",
    signalTypes: ["physical-access", "identity"],
    status: "connected",
    lastSync: new Date(Date.now() - 21_000).toISOString(),
    signalsIngested24h: 5831,
    latencyMs: 67,
    apiDocsUrl: "https://developers.google.com/wallet",
    description: "Google Wallet access cards and Android Enterprise Identity Credential API — NFC + BLE mobile credentials with Android Enterprise attestation, FIDO2 platform authenticator, and Verified Boot device health signals.",
  },
  {
    id: "swiftconnect",
    vendor: "SwiftConnect",
    product: "SwiftConnect Platform",
    category: "Mobile Credentials",
    signalTypes: ["physical-access", "identity"],
    status: "not-configured",
    lastSync: null,
    signalsIngested24h: 0,
    latencyMs: 0,
    apiDocsUrl: "https://swiftconnect.io/developers",
    description: "Mobile credential middleware platform — connects Apple Wallet, Google Wallet, and HID Mobile Access to enterprise PACS systems including Lenel, Genetec, and Software House. Enables unified mobile credential provisioning and access event aggregation.",
  },

  // ── IoT / Smart Building ──────────────────────────────────────────────────
  {
    id: "csa-matter",
    vendor: "Connectivity Standards Alliance",
    product: "Matter + Project CHIP",
    category: "IoT / Smart Building",
    signalTypes: ["physical-access", "network-posture"],
    status: "not-configured",
    lastSync: null,
    signalsIngested24h: 0,
    latencyMs: 0,
    githubUrl: "https://github.com/project-chip/connectedhomeip",
    apiDocsUrl: "https://csa-iot.org/developer-resource/",
    description: "IoT interoperability standard for smart buildings — Matter protocol provides secure device commissioning, occupancy context, smart lock events, and physical environment signals across Apple, Google, Amazon, and enterprise building automation ecosystems.",
  },
  {
    id: "johnson-controls",
    vendor: "Johnson Controls",
    product: "OpenBlue Platform",
    category: "IoT / Smart Building",
    signalTypes: ["physical-access", "operational-signals"],
    status: "not-configured",
    lastSync: null,
    signalsIngested24h: 0,
    latencyMs: 0,
    apiDocsUrl: "https://openblue.johnsoncontrols.com/",
    description: "Smart building IoT platform — HVAC, occupancy, access control, and energy data unified via OpenBlue APIs. Provides building context signals for shift-aware and location-aware Zero Trust enforcement.",
  },
  {
    id: "axis-communications",
    vendor: "Axis Communications",
    product: "AXIS Camera Station + ACAP",
    category: "IoT / Smart Building",
    signalTypes: ["physical-access"],
    status: "not-configured",
    lastSync: null,
    signalsIngested24h: 0,
    latencyMs: 0,
    githubUrl: "https://github.com/AxisCommunications",
    apiDocsUrl: "https://developer.axis.com/",
    description: "IP camera and video analytics platform — VAPIX and ACAP APIs provide real-time video event signals, tailgating detection, license plate recognition, and physical area occupancy for building access convergence.",
  },

  // ── ITSM ─────────────────────────────────────────────────────────────────
  {
    id: "servicenow",
    vendor: "ServiceNow",
    product: "ServiceNow ITSM",
    category: "ITSM",
    signalTypes: ["operational-signals"],
    status: "connected",
    lastSync: new Date(Date.now() - 90_000).toISOString(),
    signalsIngested24h: 284,
    latencyMs: 423,
    apiDocsUrl: "https://developer.servicenow.com/dev.do#!/reference/api",
    description: "IT service management — open incident context, change windows, CMDB device records, and configuration item status for operational risk assessment.",
  },
  {
    id: "jira",
    vendor: "Atlassian",
    product: "Jira Service Management",
    category: "ITSM",
    signalTypes: ["operational-signals"],
    status: "connected",
    lastSync: new Date(Date.now() - 180_000).toISOString(),
    signalsIngested24h: 121,
    latencyMs: 387,
    description: "ITSM and incident management — open ticket context and escalation signals for operational risk assessment.",
  },
  {
    id: "pagerduty",
    vendor: "PagerDuty",
    product: "PagerDuty Operations Cloud",
    category: "ITSM",
    signalTypes: ["operational-signals"],
    status: "connected",
    lastSync: new Date(Date.now() - 48_000).toISOString(),
    signalsIngested24h: 342,
    latencyMs: 198,
    githubUrl: "https://github.com/PagerDuty",
    apiDocsUrl: "https://developer.pagerduty.com/api-reference/",
    description: "Incident response and on-call management platform — real-time incident state, escalation policy, and on-call schedule signals via Events API v2 for automated alert-to-ticket workflows.",
  },
  {
    id: "opsgenie",
    vendor: "Atlassian",
    product: "Opsgenie",
    category: "ITSM",
    signalTypes: ["operational-signals"],
    status: "not-configured",
    lastSync: null,
    signalsIngested24h: 0,
    latencyMs: 0,
    apiDocsUrl: "https://docs.opsgenie.com/docs/opsgenie-api",
    description: "Alert management and on-call scheduling — Opsgenie API provides open alert context, escalation state, and on-call roster signals for operational risk correlation.",
  },
  {
    id: "freshservice",
    vendor: "Freshworks",
    product: "Freshservice ITSM",
    category: "ITSM",
    signalTypes: ["operational-signals"],
    status: "not-configured",
    lastSync: null,
    signalsIngested24h: 0,
    latencyMs: 0,
    apiDocsUrl: "https://api.freshservice.com/",
    description: "Modern ITSM platform — incident, problem, and change management with asset lifecycle tracking. REST API surfaces open ticket context and service desk escalation signals.",
  },
  {
    id: "bmc-helix",
    vendor: "BMC",
    product: "BMC Helix ITSM + SecOps",
    category: "ITSM",
    signalTypes: ["operational-signals"],
    status: "not-configured",
    lastSync: null,
    signalsIngested24h: 0,
    latencyMs: 0,
    apiDocsUrl: "https://docs.bmc.com/docs/helixplatform/rest-api-overview-1058070220.html",
    description: "Enterprise ITSM and AIOps platform — BMC Helix REST API surfaces incident state, CMDB configuration item risk, and SecOps vulnerability-to-ticket correlation signals.",
  },
  {
    id: "manageengine-servicedesk",
    vendor: "ManageEngine",
    product: "ServiceDesk Plus",
    category: "ITSM",
    signalTypes: ["operational-signals"],
    status: "not-configured",
    lastSync: null,
    signalsIngested24h: 0,
    latencyMs: 0,
    apiDocsUrl: "https://www.manageengine.com/products/service-desk/help/adminguide/api/rest-api.html",
    description: "ITSM with built-in asset management — incident and change management tied to endpoint inventory, enabling direct correlation between open tickets and device posture signals.",
  },

  // ── Infrastructure Monitoring ─────────────────────────────────────────────
  {
    id: "datadog",
    vendor: "Datadog",
    product: "Datadog Cloud Monitoring + SIEM",
    category: "Infrastructure Monitoring",
    signalTypes: ["operational-signals", "network-posture"],
    status: "connected",
    lastSync: new Date(Date.now() - 11_000).toISOString(),
    signalsIngested24h: 8934,
    latencyMs: 87,
    githubUrl: "https://github.com/DataDog",
    apiDocsUrl: "https://docs.datadoghq.com/api/latest/",
    description: "Full-stack observability and security monitoring — infrastructure metrics, APM, log management, and Cloud SIEM with Events API for real-time operational signal correlation.",
  },
  {
    id: "grafana",
    vendor: "Grafana Labs",
    product: "Grafana Cloud + Alerting",
    category: "Infrastructure Monitoring",
    signalTypes: ["operational-signals"],
    status: "connected",
    lastSync: new Date(Date.now() - 34_000).toISOString(),
    signalsIngested24h: 4102,
    latencyMs: 156,
    githubUrl: "https://github.com/grafana/grafana",
    apiDocsUrl: "https://grafana.com/docs/grafana/latest/developers/http_api/",
    description: "Open-source observability platform — unified metrics, logs, and traces with Alertmanager-compatible alert rules. HTTP API surfaces active alert state and dashboard annotation events.",
  },
  {
    id: "prometheus",
    vendor: "CNCF (OpenSource)",
    product: "Prometheus + Alertmanager",
    category: "Infrastructure Monitoring",
    signalTypes: ["operational-signals"],
    status: "connected",
    lastSync: new Date(Date.now() - 28_000).toISOString(),
    signalsIngested24h: 3847,
    latencyMs: 62,
    githubUrl: "https://github.com/prometheus/prometheus",
    apiDocsUrl: "https://prometheus.io/docs/prometheus/latest/querying/api/",
    description: "Open-source metrics monitoring and alerting — PromQL query API surfaces infrastructure health, SLO breach signals, and Alertmanager webhook integration for real-time operational risk.",
  },
  {
    id: "prtg",
    vendor: "Paessler",
    product: "PRTG Network Monitor",
    category: "Infrastructure Monitoring",
    signalTypes: ["operational-signals", "network-posture"],
    status: "not-configured",
    lastSync: null,
    signalsIngested24h: 0,
    latencyMs: 0,
    apiDocsUrl: "https://www.paessler.com/manuals/prtg/http_api",
    description: "Network and device monitoring platform — PRTG HTTP API surfaces sensor state, device availability, bandwidth utilization, and alert history for network posture assessment.",
  },
  {
    id: "thousand-eyes",
    vendor: "Cisco",
    product: "ThousandEyes",
    category: "Infrastructure Monitoring",
    signalTypes: ["network-posture", "operational-signals"],
    status: "not-configured",
    lastSync: null,
    signalsIngested24h: 0,
    latencyMs: 0,
    apiDocsUrl: "https://developer.cisco.com/docs/thousandeyes/",
    description: "Network path intelligence platform — end-to-end visibility into ISP, cloud, SaaS, and enterprise network paths. API surfaces packet loss, latency, and SaaS reachability signals.",
  },
  {
    id: "new-relic",
    vendor: "New Relic",
    product: "New Relic One",
    category: "Infrastructure Monitoring",
    signalTypes: ["operational-signals"],
    status: "not-configured",
    lastSync: null,
    signalsIngested24h: 0,
    latencyMs: 0,
    githubUrl: "https://github.com/newrelic",
    apiDocsUrl: "https://docs.newrelic.com/docs/apis/nerdgraph/get-started/introduction-new-relic-nerdgraph/",
    description: "Observability platform — NerdGraph GraphQL API surfaces application performance, infrastructure health, and alert condition signals for operational risk correlation.",
  },
  {
    id: "dynatrace",
    vendor: "Dynatrace",
    product: "Dynatrace Platform",
    category: "Infrastructure Monitoring",
    signalTypes: ["operational-signals"],
    status: "not-configured",
    lastSync: null,
    signalsIngested24h: 0,
    latencyMs: 0,
    apiDocsUrl: "https://docs.dynatrace.com/docs/dynatrace-api",
    description: "AIOps and full-stack observability — AI-powered problem detection across applications, microservices, and infrastructure with Dynatrace API for causal analysis signal export.",
  },
  {
    id: "zabbix",
    vendor: "Zabbix LLC",
    product: "Zabbix",
    category: "Infrastructure Monitoring",
    signalTypes: ["operational-signals", "network-posture"],
    status: "not-configured",
    lastSync: null,
    signalsIngested24h: 0,
    latencyMs: 0,
    githubUrl: "https://github.com/zabbix/zabbix",
    apiDocsUrl: "https://www.zabbix.com/documentation/current/en/manual/api",
    description: "Open-source enterprise monitoring — network device discovery, SNMP/IPMI/agent-based monitoring with Zabbix API for infrastructure health and alert state signals.",
  },

  // ── Cellular / eSIM ───────────────────────────────────────────────────────
  {
    id: "twilio-super-sim",
    vendor: "Twilio",
    product: "Twilio Super SIM",
    category: "Cellular / eSIM",
    signalTypes: ["network-posture"],
    status: "connected",
    lastSync: new Date(Date.now() - 22_000).toISOString(),
    signalsIngested24h: 2841,
    latencyMs: 143,
    githubUrl: "https://github.com/twilio",
    apiDocsUrl: "https://www.twilio.com/docs/iot/supersim",
    description: "Programmable cellular IoT SIM/eSIM — global multi-carrier connectivity with REST API for real-time connection state, data usage, roaming status, and device reachability signals. Critical for post-exit device tracking on cellular-capable hardware.",
  },
  {
    id: "soracom",
    vendor: "SORACOM",
    product: "Soracom IoT Platform",
    category: "Cellular / eSIM",
    signalTypes: ["network-posture"],
    status: "connected",
    lastSync: new Date(Date.now() - 41_000).toISOString(),
    signalsIngested24h: 1923,
    latencyMs: 187,
    githubUrl: "https://github.com/soracom",
    apiDocsUrl: "https://developers.soracom.io/en/docs/api/",
    description: "Global IoT SIM/eSIM platform with cloud-native APIs — subscriber management, real-time connection monitoring, Harvest data collection, and Beam protocol conversion for device telemetry pipelines.",
  },
  {
    id: "verizon-thingspace",
    vendor: "Verizon",
    product: "ThingSpace IoT Platform",
    category: "Cellular / eSIM",
    signalTypes: ["network-posture"],
    status: "not-configured",
    lastSync: null,
    signalsIngested24h: 0,
    latencyMs: 0,
    apiDocsUrl: "https://thingspace.verizon.com/developer/",
    description: "Verizon's IoT connectivity and orchestration platform — eSIM profile switching, device activation, global IoT management, and ThingSpace API for real-time connectivity and location signals.",
  },
  {
    id: "att-control-center",
    vendor: "AT&T",
    product: "AT&T Control Center",
    category: "Cellular / eSIM",
    signalTypes: ["network-posture"],
    status: "not-configured",
    lastSync: null,
    signalsIngested24h: 0,
    latencyMs: 0,
    apiDocsUrl: "https://marketplace.att.com/products/att-control-center",
    description: "AT&T IoT device lifecycle management — real-time device activation, data usage monitoring, geo-specific usage alerts, automation rules, and API integration for M2M connectivity signals.",
  },
  {
    id: "cisco-iot-cc",
    vendor: "Cisco",
    product: "Cisco IoT Control Center",
    category: "Cellular / eSIM",
    signalTypes: ["network-posture"],
    status: "not-configured",
    lastSync: null,
    signalsIngested24h: 0,
    latencyMs: 0,
    apiDocsUrl: "https://developer.cisco.com/iot/",
    description: "Carrier IoT connectivity management platform — alerts on usage threshold breach, location change, fraud detection, and data anomaly. Supports multi-carrier M2M/eSIM orchestration.",
  },
  {
    id: "hologram",
    vendor: "Hologram",
    product: "Hologram IoT Platform",
    category: "Cellular / eSIM",
    signalTypes: ["network-posture"],
    status: "not-configured",
    lastSync: null,
    signalsIngested24h: 0,
    latencyMs: 0,
    githubUrl: "https://github.com/hologram-io",
    apiDocsUrl: "https://www.hologram.io/references/api",
    description: "Developer-friendly IoT cellular connectivity — global SIM with REST API for device state, data usage, last-seen location, and webhook-based connectivity event delivery for real-time device tracking.",
  },
  {
    id: "kore-wireless",
    vendor: "KORE Wireless",
    product: "KORE ONE Platform",
    category: "Cellular / eSIM",
    signalTypes: ["network-posture"],
    status: "not-configured",
    lastSync: null,
    signalsIngested24h: 0,
    latencyMs: 0,
    apiDocsUrl: "https://kore.com/platform/",
    description: "Managed enterprise IoT connectivity — global eSIM, carrier selection intelligence, and KORE ONE API for device diagnostics, connectivity state, and real-time usage anomaly signals.",
  },
  {
    id: "emnify",
    vendor: "EMnify",
    product: "EMnify Cloud Connect",
    category: "Cellular / eSIM",
    signalTypes: ["network-posture"],
    status: "not-configured",
    lastSync: null,
    signalsIngested24h: 0,
    latencyMs: 0,
    githubUrl: "https://github.com/emnify",
    apiDocsUrl: "https://cdn.emnify.net/api/doc/index.html",
    description: "Cloud-native cellular IoT API platform — SIM lifecycle management, real-time connectivity events, traffic policy enforcement, and webhook delivery for device online/offline state signals.",
  },
  {
    id: "eseye",
    vendor: "Eseye",
    product: "AnyNet+ eSIM",
    category: "Cellular / eSIM",
    signalTypes: ["network-posture"],
    status: "not-configured",
    lastSync: null,
    signalsIngested24h: 0,
    latencyMs: 0,
    apiDocsUrl: "https://eseye.com/developers/",
    description: "Enterprise eSIM and global IoT connectivity — AnyNet+ eSIM with intelligent carrier selection and REST API for device connectivity state, session events, and location-based roaming signals.",
  },

  // ── SOAR / Automation ─────────────────────────────────────────────────────
  {
    id: "tines",
    vendor: "Tines",
    product: "Tines Security Automation",
    category: "SOAR / Automation",
    signalTypes: ["operational-signals"],
    status: "connected",
    lastSync: new Date(Date.now() - 38_000).toISOString(),
    signalsIngested24h: 1247,
    latencyMs: 112,
    githubUrl: "https://github.com/tines",
    apiDocsUrl: "https://www.tines.com/api-reference",
    description: "No-code security automation platform — webhook-based story triggers surface active playbook state, automated action results, and human-in-the-loop escalation signals for operational risk correlation.",
  },
  {
    id: "torq",
    vendor: "Torq",
    product: "Torq HyperSOAR",
    category: "SOAR / Automation",
    signalTypes: ["operational-signals"],
    status: "not-configured",
    lastSync: null,
    signalsIngested24h: 0,
    latencyMs: 0,
    apiDocsUrl: "https://docs.torq.io/",
    description: "AI-powered SOAR platform — autonomous security workflows that trigger on identity, device, and threat signals. HyperSOAR executes remediation faster than human-driven playbooks.",
  },
  {
    id: "aws-eventbridge",
    vendor: "Amazon Web Services",
    product: "AWS EventBridge",
    category: "SOAR / Automation",
    signalTypes: ["operational-signals"],
    status: "not-configured",
    lastSync: null,
    signalsIngested24h: 0,
    latencyMs: 0,
    apiDocsUrl: "https://docs.aws.amazon.com/eventbridge/latest/APIReference/Welcome.html",
    description: "Serverless event bus — routes signals from GuardDuty, Security Hub, IAM Identity Center, and 200+ SaaS partners to SignalGrid via EventBridge rules and API destinations.",
  },
  {
    id: "azure-event-grid",
    vendor: "Microsoft",
    product: "Azure Event Grid + Logic Apps",
    category: "SOAR / Automation",
    signalTypes: ["operational-signals"],
    status: "not-configured",
    lastSync: null,
    signalsIngested24h: 0,
    latencyMs: 0,
    apiDocsUrl: "https://learn.microsoft.com/en-us/azure/event-grid/rest-overview",
    description: "Azure event routing and workflow automation — push-based event delivery from Microsoft Sentinel, Entra ID, Defender, and Azure Security Center to SignalGrid via Event Grid subscriptions.",
  },
  {
    id: "google-pubsub",
    vendor: "Google Cloud",
    product: "Google Pub/Sub + Security Command Center",
    category: "SOAR / Automation",
    signalTypes: ["operational-signals"],
    status: "not-configured",
    lastSync: null,
    signalsIngested24h: 0,
    latencyMs: 0,
    apiDocsUrl: "https://cloud.google.com/pubsub/docs/reference/rest",
    description: "Google Cloud messaging and security event streaming — Pub/Sub delivers Security Command Center findings, Chronicle alerts, and Cloud Armor security events to SignalGrid in real time.",
  },

  // ── Disaster Recovery / Business Continuity ───────────────────────────────
  {
    id: "veeam",
    vendor: "Veeam",
    product: "Veeam Backup & Replication",
    category: "Disaster Recovery / BC",
    signalTypes: ["operational-signals"],
    status: "connected",
    lastSync: new Date(Date.now() - 61_000).toISOString(),
    signalsIngested24h: 892,
    latencyMs: 234,
    githubUrl: "https://github.com/VeeamHub",
    apiDocsUrl: "https://helpcenter.veeam.com/docs/backup/rest/",
    description: "Enterprise backup and replication — Veeam REST API surfaces backup job state, recovery point age, RTO/RPO health, and infrastructure protection coverage. Backup failure or RPO breach signals feed directly into operational risk decisions.",
  },
  {
    id: "zerto",
    vendor: "Zerto (HPE)",
    product: "Zerto IT Resilience Platform",
    category: "Disaster Recovery / BC",
    signalTypes: ["operational-signals"],
    status: "connected",
    lastSync: new Date(Date.now() - 88_000).toISOString(),
    signalsIngested24h: 541,
    latencyMs: 317,
    apiDocsUrl: "https://help.zerto.com/bundle/API.HTML.k10u5/page/Content/API_Overview/Overview.htm",
    description: "Continuous replication and disaster recovery orchestration — Zerto API surfaces replication lag, failover readiness, VPG health, and site connectivity for near-zero RPO infrastructure risk signals.",
  },
  {
    id: "rubrik",
    vendor: "Rubrik",
    product: "Rubrik Security Cloud",
    category: "Disaster Recovery / BC",
    signalTypes: ["operational-signals"],
    status: "not-configured",
    lastSync: null,
    signalsIngested24h: 0,
    latencyMs: 0,
    githubUrl: "https://github.com/rubrikinc",
    apiDocsUrl: "https://www.rubrik.com/api",
    description: "Data security and cloud-native backup — Rubrik RSC API provides backup compliance scores, anomaly detection (ransomware indicators), data classification findings, and recovery readiness signals.",
  },
  {
    id: "cohesity",
    vendor: "Cohesity",
    product: "Cohesity DataProtect",
    category: "Disaster Recovery / BC",
    signalTypes: ["operational-signals"],
    status: "not-configured",
    lastSync: null,
    signalsIngested24h: 0,
    latencyMs: 0,
    githubUrl: "https://github.com/cohesity",
    apiDocsUrl: "https://developer.cohesity.com/",
    description: "Hyperconverged secondary storage and data protection — Cohesity REST API surfaces backup policy compliance, DataHawk threat intelligence, and anomaly detection signals for operational resilience monitoring.",
  },
  {
    id: "commvault",
    vendor: "Commvault",
    product: "Commvault Complete Data Protection",
    category: "Disaster Recovery / BC",
    signalTypes: ["operational-signals"],
    status: "not-configured",
    lastSync: null,
    signalsIngested24h: 0,
    latencyMs: 0,
    apiDocsUrl: "https://documentation.commvault.com/11.24/essential/45551_rest_api_overview.html",
    description: "Enterprise data protection and cyber resilience — Commvault API exposes job health, SLA compliance, recovery validation results, and Ransomware Protection risk scores across on-premise and cloud workloads.",
  },
  {
    id: "aws-backup-dr",
    vendor: "Amazon Web Services",
    product: "AWS Backup + Elastic Disaster Recovery",
    category: "Disaster Recovery / BC",
    signalTypes: ["operational-signals"],
    status: "not-configured",
    lastSync: null,
    signalsIngested24h: 0,
    latencyMs: 0,
    apiDocsUrl: "https://docs.aws.amazon.com/aws-backup/latest/devguide/api-reference.html",
    description: "Managed AWS backup and application-level DR — AWS Backup API surfaces vault protection coverage and compliance reports; Elastic Disaster Recovery provides replication state and recovery readiness signals for AWS-hosted workloads.",
  },
  {
    id: "azure-site-recovery",
    vendor: "Microsoft",
    product: "Azure Site Recovery",
    category: "Disaster Recovery / BC",
    signalTypes: ["operational-signals"],
    status: "not-configured",
    lastSync: null,
    signalsIngested24h: 0,
    latencyMs: 0,
    apiDocsUrl: "https://learn.microsoft.com/en-us/rest/api/recoveryservices/",
    description: "Microsoft Azure disaster recovery orchestration — ASR REST API provides replication health, RPO warnings, failover readiness state, and infrastructure dependency mapping signals for hybrid and cloud workloads.",
  },
  {
    id: "veritas-netbackup",
    vendor: "Veritas",
    product: "Veritas NetBackup",
    category: "Disaster Recovery / BC",
    signalTypes: ["operational-signals"],
    status: "not-configured",
    lastSync: null,
    signalsIngested24h: 0,
    latencyMs: 0,
    apiDocsUrl: "https://sort.veritas.com/public/documents/nbu/8.3/windowsandunix/productguides/html/index.html",
    description: "Enterprise backup for large-scale heterogeneous environments — NetBackup REST API surfaces policy compliance, job status, catalog integrity, and anomaly detection signals across physical, virtual, and cloud infrastructure.",
  },
  {
    id: "acronis",
    vendor: "Acronis",
    product: "Acronis Cyber Protect",
    category: "Disaster Recovery / BC",
    signalTypes: ["operational-signals"],
    status: "not-configured",
    lastSync: null,
    signalsIngested24h: 0,
    latencyMs: 0,
    apiDocsUrl: "https://developer.acronis.com/",
    description: "Integrated backup and cybersecurity platform — Acronis API provides backup protection status, AI-based ransomware detection signals, vulnerability assessment results, and endpoint protection health in a unified risk feed.",
  },

  // ── GRC / Compliance ──────────────────────────────────────────────────────
  {
    id: "servicenow-grc",
    vendor: "ServiceNow",
    product: "ServiceNow GRC / IRM",
    category: "GRC / Compliance",
    signalTypes: ["operational-signals"],
    status: "connected",
    lastSync: new Date(Date.now() - 72_000).toISOString(),
    signalsIngested24h: 673,
    latencyMs: 291,
    apiDocsUrl: "https://developer.servicenow.com/dev.do#!/reference/api/tokyo/rest/grc-api",
    description: "Integrated Risk Management and GRC — ServiceNow GRC API surfaces control test failures, risk register changes, policy exception approvals, and continuous compliance monitoring signals for real-time governance context.",
  },
  {
    id: "rsa-archer",
    vendor: "RSA",
    product: "RSA Archer GRC Platform",
    category: "GRC / Compliance",
    signalTypes: ["operational-signals"],
    status: "not-configured",
    lastSync: null,
    signalsIngested24h: 0,
    latencyMs: 0,
    apiDocsUrl: "https://community.rsa.com/s/article/Archer-REST-API-Reference-Guide",
    description: "Enterprise GRC and third-party risk management — Archer REST API provides control assessment status, audit finding severity, vendor risk scores, and policy exception signals for compliance-aware access decisions.",
  },
  {
    id: "qualys-vmdr",
    vendor: "Qualys",
    product: "Qualys VMDR",
    category: "GRC / Compliance",
    signalTypes: ["operational-signals", "device-posture"],
    status: "connected",
    lastSync: new Date(Date.now() - 45_000).toISOString(),
    signalsIngested24h: 2341,
    latencyMs: 178,
    apiDocsUrl: "https://www.qualys.com/documentation/",
    description: "Vulnerability Management, Detection & Response — Qualys VMDR API provides real-time asset vulnerability scores, CVSS severity distributions, patch compliance rates, and DISA STIG check results for device risk decisions.",
  },
  {
    id: "rapid7-insightvm",
    vendor: "Rapid7",
    product: "Rapid7 InsightVM",
    category: "GRC / Compliance",
    signalTypes: ["operational-signals", "device-posture"],
    status: "not-configured",
    lastSync: null,
    signalsIngested24h: 0,
    latencyMs: 0,
    githubUrl: "https://github.com/rapid7",
    apiDocsUrl: "https://help.rapid7.com/insightvm/en-us/api/index.html",
    description: "Live vulnerability and risk management — InsightVM REST API surfaces asset risk scores, active exploit correlation, remediation SLA tracking, and CIS Benchmark compliance signals for continuous posture evaluation.",
  },
  {
    id: "tenable",
    vendor: "Tenable",
    product: "Tenable.io / Tenable.sc",
    category: "GRC / Compliance",
    signalTypes: ["operational-signals", "device-posture"],
    status: "not-configured",
    lastSync: null,
    signalsIngested24h: 0,
    latencyMs: 0,
    apiDocsUrl: "https://developer.tenable.com/reference/navigate",
    description: "Exposure management platform — Tenable API provides vulnerability exposure scores, DISA STIG compliance audit results, asset criticality ratings, and attack path analysis for risk-informed access decisions.",
  },
  {
    id: "drata",
    vendor: "Drata",
    product: "Drata Compliance Automation",
    category: "GRC / Compliance",
    signalTypes: ["operational-signals"],
    status: "not-configured",
    lastSync: null,
    signalsIngested24h: 0,
    latencyMs: 0,
    githubUrl: "https://github.com/drata",
    apiDocsUrl: "https://drata.com/developers",
    description: "Continuous compliance automation for SOC 2, ISO 27001, HIPAA, GDPR, and FedRAMP — Drata API surfaces control health status, evidence collection gaps, and compliance posture changes as real-time operational risk signals.",
  },
  {
    id: "vanta",
    vendor: "Vanta",
    product: "Vanta Trust Management",
    category: "GRC / Compliance",
    signalTypes: ["operational-signals"],
    status: "not-configured",
    lastSync: null,
    signalsIngested24h: 0,
    latencyMs: 0,
    apiDocsUrl: "https://developer.vanta.com/",
    description: "Automated security and compliance monitoring — Vanta API provides real-time compliance control pass/fail state, employee security training completion, and vendor review status signals across SOC 2, HIPAA, and PCI frameworks.",
  },
  {
    id: "auditboard",
    vendor: "AuditBoard",
    product: "AuditBoard Connected Risk Platform",
    category: "GRC / Compliance",
    signalTypes: ["operational-signals"],
    status: "not-configured",
    lastSync: null,
    signalsIngested24h: 0,
    latencyMs: 0,
    apiDocsUrl: "https://docs.auditboard.com/",
    description: "Connected risk, audit, and compliance management — AuditBoard API surfaces audit finding severity, control effectiveness ratings, risk register changes, and SOX/operational audit signals for governance-aware decisions.",
  },
  {
    id: "disa-scap",
    vendor: "DISA",
    product: "SCAP Compliance Checker / STIG Viewer",
    category: "GRC / Compliance",
    signalTypes: ["operational-signals", "device-posture"],
    status: "not-configured",
    lastSync: null,
    signalsIngested24h: 0,
    latencyMs: 0,
    apiDocsUrl: "https://public.cyber.mil/stigs/",
    description: "Defense Information Systems Agency hardening standards — SCAP Compliance Checker results provide STIG finding counts, CAT I/II/III severity breakdowns, and XCCDF checklist compliance state for DoD IL2–IL5 access decisions.",
  },
];

// The integration catalog is immutable for the process lifetime, so serialize
// it once at module load instead of re-running JSON.stringify over ~149 objects
// on every request, and mark the response cacheable (overriding the global
// no-store) since it never changes between deploys.
//
// Transparency: this is an ILLUSTRATIVE catalog. The per-item `status`
// ("connected"/"degraded"), `signalsIngested24h`, `latencyMs`, and `lastSync`
// values are synthetic demo fixtures fixed at process start — not live
// connections or real ingestion volumes. No live vendor call is ever made. The
// envelope carries an explicit `note` and `demo` flag so any consumer of this
// machine-readable surface sees the disclaimer, matching the rest of the
// fixture-backed product.
const INTEGRATIONS_BODY = JSON.stringify({
  demo: true,
  note: "Illustrative catalog — per-item status, ingestion volumes, latency, and lastSync are synthetic demo fixtures (fixed at process start), not live connections. No live vendor call is made.",
  integrations: INTEGRATIONS,
});

router.get("/integrations", (_req, res) => {
  res.setHeader("cache-control", "public, max-age=300");
  res.type("application/json").send(INTEGRATIONS_BODY);
});

router.get("/integrations/:id", (req, res) => {
  const parsed = GetIntegrationParams.safeParse(req.params);
  if (!parsed.success) {
    res.status(400).json({ error: "validation", message: "Invalid integration ID" });
    return;
  }

  const integration = INTEGRATIONS.find((i) => i.id === parsed.data.id);
  if (!integration) {
    res.status(404).json({ error: "not_found", message: "Integration not found" });
    return;
  }

  res.json(integration);
});

export default router;
