import { Router, type IRouter } from "express";
import { GetIntegrationParams } from "@workspace/api-zod";

const router: IRouter = Router();

const INTEGRATIONS = [
  // ── IGA / Identity Governance & Administration ────────────────────────────
  {
    id: "sailpoint",
    vendor: "SailPoint",
    product: "Identity Security Cloud",
    category: "IGA / IDP",
    signalTypes: ["identity"],
    status: "connected",
    lastSync: new Date(Date.now() - 6_000).toISOString(),
    signalsIngested24h: 8421,
    latencyMs: 112,
    githubUrl: "https://github.com/sailpoint-oss",
    apiDocsUrl: "https://developer.sailpoint.com/docs/api",
    description: "Enterprise IGA — lifecycle management, access certification, and role governance across all enterprise apps. One of the leading Gartner Magic Quadrant Leaders for IGA.",
  },
  {
    id: "saviynt",
    vendor: "Saviynt",
    product: "Identity Cloud",
    category: "IGA / IDP",
    signalTypes: ["identity"],
    status: "connected",
    lastSync: new Date(Date.now() - 14_000).toISOString(),
    signalsIngested24h: 6203,
    latencyMs: 98,
    description: "Cloud-native IGA and application access governance — provisioning, access requests, and SoD controls.",
  },
  {
    id: "okta",
    vendor: "Okta",
    product: "Workforce Identity + Lifecycle Management",
    category: "IGA / IDP",
    signalTypes: ["identity"],
    status: "connected",
    lastSync: new Date(Date.now() - 8_000).toISOString(),
    signalsIngested24h: 5621,
    latencyMs: 95,
    githubUrl: "https://github.com/okta",
    apiDocsUrl: "https://developer.okta.com/docs/api",
    description: "Identity provider and lifecycle management — SSO, MFA, and automated provisioning for workforce identities.",
  },
  {
    id: "microsoft-entra",
    vendor: "Microsoft",
    product: "Entra ID + Identity Governance",
    category: "IGA / IDP",
    signalTypes: ["identity", "device-posture"],
    status: "connected",
    lastSync: new Date(Date.now() - 12_000).toISOString(),
    signalsIngested24h: 11_847,
    latencyMs: 143,
    apiDocsUrl: "https://learn.microsoft.com/en-us/graph/api/overview",
    description: "Azure AD identity signals — MFA status, conditional access policies, identity risk scores, and device compliance. Microsoft Graph API integration.",
  },
  {
    id: "auth0",
    vendor: "Okta",
    product: "Auth0",
    category: "IGA / IDP",
    signalTypes: ["identity"],
    status: "connected",
    lastSync: new Date(Date.now() - 55_000).toISOString(),
    signalsIngested24h: 3102,
    latencyMs: 88,
    githubUrl: "https://github.com/auth0",
    apiDocsUrl: "https://auth0.com/docs/api",
    description: "Developer-focused CIAM platform — authentication, authorization, and user management with extensive SDK ecosystem.",
  },
  {
    id: "keycloak",
    vendor: "Red Hat",
    product: "Keycloak",
    category: "IGA / IDP",
    signalTypes: ["identity"],
    status: "connected",
    lastSync: new Date(Date.now() - 40_000).toISOString(),
    signalsIngested24h: 2841,
    latencyMs: 134,
    githubUrl: "https://github.com/keycloak/keycloak",
    description: "Open-source IAM — SSO, OIDC/SAML federation, user federation, and fine-grained authorization. Self-hosted identity for enterprises requiring data sovereignty.",
  },
  {
    id: "teleport",
    vendor: "Gravitational",
    product: "Teleport",
    category: "IGA / IDP",
    signalTypes: ["identity", "session-context"],
    status: "connected",
    lastSync: new Date(Date.now() - 28_000).toISOString(),
    signalsIngested24h: 1923,
    latencyMs: 76,
    githubUrl: "https://github.com/gravitational/teleport",
    apiDocsUrl: "https://goteleport.com/docs/api/",
    description: "Zero Trust access platform for infrastructure — SSH, Kubernetes, databases, and internal apps with full session recording and audit trail.",
  },
  {
    id: "zitadel",
    vendor: "ZITADEL",
    product: "ZITADEL Cloud",
    category: "IGA / IDP",
    signalTypes: ["identity"],
    status: "not-configured",
    lastSync: null,
    signalsIngested24h: 0,
    latencyMs: 0,
    githubUrl: "https://github.com/zitadel/zitadel",
    description: "Open-source identity infrastructure — multi-tenancy, passwordless auth, and fine-grained permission system built for cloud-native architectures.",
  },
  {
    id: "radiantone",
    vendor: "Radiant Logic",
    product: "RadiantOne Identity Data Platform",
    category: "IGA / IDP",
    signalTypes: ["identity"],
    status: "connected",
    lastSync: new Date(Date.now() - 22_000).toISOString(),
    signalsIngested24h: 3812,
    latencyMs: 167,
    description: "Identity data fabric — unifies identity data from AD, LDAP, databases, and cloud directories into a single identity view.",
  },
  {
    id: "one-identity",
    vendor: "One Identity",
    product: "One Identity Manager",
    category: "IGA / IDP",
    signalTypes: ["identity"],
    status: "degraded",
    lastSync: new Date(Date.now() - 480_000).toISOString(),
    signalsIngested24h: 891,
    latencyMs: 2340,
    errorMessage: "SCIM endpoint returning 503 — retrying with exponential backoff",
    description: "IGA platform — role management, access request workflows, and privileged account governance.",
  },
  {
    id: "manageengine-iga",
    vendor: "ManageEngine",
    product: "ADManager Plus + AD360",
    category: "IGA / IDP",
    signalTypes: ["identity", "operational-signals"],
    status: "connected",
    lastSync: new Date(Date.now() - 35_000).toISOString(),
    signalsIngested24h: 2674,
    latencyMs: 231,
    apiDocsUrl: "https://www.manageengine.com/products/active-directory-manager/help/api-v2/",
    description: "Active Directory management and identity governance — user lifecycle, group management, and compliance reporting.",
  },
  {
    id: "oracle-idm",
    vendor: "Oracle",
    product: "Oracle Identity Governance",
    category: "IGA / IDP",
    signalTypes: ["identity"],
    status: "not-configured",
    lastSync: null,
    signalsIngested24h: 0,
    latencyMs: 0,
    description: "Oracle IDM — automated provisioning, access certification, and role management for Oracle and non-Oracle applications.",
  },
  {
    id: "netwrix",
    vendor: "Netwrix",
    product: "Netwrix Directory Manager",
    category: "IGA / IDP",
    signalTypes: ["identity", "operational-signals"],
    status: "not-configured",
    lastSync: null,
    signalsIngested24h: 0,
    latencyMs: 0,
    description: "Directory lifecycle management across AD, Entra ID, and Google Workspace — provisioning and access delegation.",
  },
  {
    id: "rsa-governance",
    vendor: "RSA",
    product: "RSA Governance & Lifecycle",
    category: "IGA / IDP",
    signalTypes: ["identity"],
    status: "not-configured",
    lastSync: null,
    signalsIngested24h: 0,
    latencyMs: 0,
    description: "Risk-aware IGA — access request management, policy enforcement, and compliance reporting.",
  },
  {
    id: "ibm-verify",
    vendor: "IBM",
    product: "IBM Security Verify Governance",
    category: "IGA / IDP",
    signalTypes: ["identity"],
    status: "not-configured",
    lastSync: null,
    signalsIngested24h: 0,
    latencyMs: 0,
    description: "IBM IGA — access certification, role management, and SoD enforcement across hybrid cloud environments.",
  },
  {
    id: "pathlock",
    vendor: "Pathlock",
    product: "Pathlock Cloud",
    category: "IGA / IDP",
    signalTypes: ["identity", "operational-signals"],
    status: "not-configured",
    lastSync: null,
    signalsIngested24h: 0,
    latencyMs: 0,
    description: "Fine-grained access governance for SAP, Oracle, and business-critical apps — SoD controls and audit readiness.",
  },
  {
    id: "imprivata",
    vendor: "Imprivata",
    product: "Imprivata OneSign",
    category: "IGA / IDP",
    signalTypes: ["identity", "physical-access"],
    status: "connected",
    lastSync: new Date(Date.now() - 18_000).toISOString(),
    signalsIngested24h: 4102,
    latencyMs: 109,
    apiDocsUrl: "https://www.imprivata.com/platform/api-integrations",
    description: "Healthcare-focused SSO and authentication for shared workstations — tap-and-go badge login, virtual desktop, and physical/digital access convergence for clinical workflows.",
  },

  // ── MDM / UEM ─────────────────────────────────────────────────────────────
  {
    id: "intune",
    vendor: "Microsoft",
    product: "Microsoft Intune",
    category: "MDM / UEM",
    signalTypes: ["device-posture"],
    status: "connected",
    lastSync: new Date(Date.now() - 9_000).toISOString(),
    signalsIngested24h: 4203,
    latencyMs: 187,
    apiDocsUrl: "https://learn.microsoft.com/en-us/graph/api/resources/intune-graph-overview",
    description: "Cloud-based UEM — device compliance, app management, and endpoint protection for Windows, macOS, iOS, and Android via Microsoft Graph API.",
  },
  {
    id: "jamf",
    vendor: "Jamf",
    product: "Jamf Pro",
    category: "MDM / UEM",
    signalTypes: ["device-posture"],
    status: "degraded",
    lastSync: new Date(Date.now() - 600_000).toISOString(),
    signalsIngested24h: 341,
    latencyMs: 1840,
    errorMessage: "API rate limit approaching — throttling signal ingestion",
    apiDocsUrl: "https://developer.jamf.com/jamf-pro/docs",
    description: "Apple-focused MDM — device enrollment, configuration profiles, and compliance for Mac, iPhone, and iPad fleets.",
  },
  {
    id: "kandji",
    vendor: "Kandji",
    product: "Kandji Device Management",
    category: "MDM / UEM",
    signalTypes: ["device-posture"],
    status: "connected",
    lastSync: new Date(Date.now() - 32_000).toISOString(),
    signalsIngested24h: 1847,
    latencyMs: 142,
    apiDocsUrl: "https://api.kandji.io",
    description: "Modern Apple MDM with one-click compliance blueprints — automated remediation, Liftoff zero-touch deployment, and real-time device health monitoring.",
  },
  {
    id: "workspace-one",
    vendor: "Omnissa (VMware)",
    product: "Workspace ONE UEM",
    category: "MDM / UEM",
    signalTypes: ["device-posture", "session-context"],
    status: "connected",
    lastSync: new Date(Date.now() - 30_000).toISOString(),
    signalsIngested24h: 2187,
    latencyMs: 265,
    apiDocsUrl: "https://developer.omnissa.com/apis/workspace-one-uem",
    description: "Unified endpoint management across all device types — compliance enforcement and app delivery for frontline workers.",
  },
  {
    id: "fleet",
    vendor: "FleetDM",
    product: "Fleet MDM",
    category: "MDM / UEM",
    signalTypes: ["device-posture"],
    status: "connected",
    lastSync: new Date(Date.now() - 45_000).toISOString(),
    signalsIngested24h: 1842,
    latencyMs: 312,
    githubUrl: "https://github.com/fleetdm/fleet",
    description: "Open-source MDM and osquery fleet management — GitOps-driven endpoint configuration, real-time device telemetry, and compliance posture for macOS, Windows, Linux, iOS, and Android.",
  },
  {
    id: "hexnode",
    vendor: "Mitsogo (Hexnode)",
    product: "Hexnode UEM",
    category: "MDM / UEM",
    signalTypes: ["device-posture", "session-context"],
    status: "connected",
    lastSync: new Date(Date.now() - 60_000).toISOString(),
    signalsIngested24h: 892,
    latencyMs: 341,
    apiDocsUrl: "https://www.hexnode.com/mobile-device-management/help/hexnode-api/",
    description: "Multi-platform UEM with kiosk management — purpose-built for shared and frontline device deployments.",
  },
  {
    id: "tanium",
    vendor: "Tanium",
    product: "Tanium Autonomous IT Platform",
    category: "MDM / UEM",
    signalTypes: ["device-posture", "operational-signals"],
    status: "connected",
    lastSync: new Date(Date.now() - 20_000).toISOString(),
    signalsIngested24h: 672,
    latencyMs: 61,
    description: "Real-time endpoint visibility and control — sub-15-second device query latency across 100k+ endpoints via linear-chain architecture.",
  },
  {
    id: "kolide",
    vendor: "Kolide",
    product: "Kolide Device Trust",
    category: "MDM / UEM",
    signalTypes: ["device-posture"],
    status: "connected",
    lastSync: new Date(Date.now() - 50_000).toISOString(),
    signalsIngested24h: 1203,
    latencyMs: 198,
    githubUrl: "https://github.com/kolide/launcher",
    description: "Honest security tool — osquery-powered device trust with user-facing transparency. Blocks SSO access when devices fall out of compliance.",
  },
  {
    id: "santa",
    vendor: "Google",
    product: "Santa (macOS)",
    category: "MDM / UEM",
    signalTypes: ["device-posture"],
    status: "connected",
    lastSync: new Date(Date.now() - 75_000).toISOString(),
    signalsIngested24h: 847,
    latencyMs: 89,
    githubUrl: "https://github.com/google/santa",
    description: "Google's open-source macOS binary authorization system — allowlist/denylist enforcement with centralized sync server for enterprise fleets.",
  },
  {
    id: "osquery",
    vendor: "Meta (OpenSource)",
    product: "osquery",
    category: "MDM / UEM",
    signalTypes: ["device-posture", "operational-signals"],
    status: "connected",
    lastSync: new Date(Date.now() - 15_000).toISOString(),
    signalsIngested24h: 3412,
    latencyMs: 44,
    githubUrl: "https://github.com/osquery/osquery",
    description: "SQL-powered endpoint telemetry engine — query any device attribute (processes, network, files, hardware) using standard SQL across your entire fleet.",
  },
  {
    id: "ivanti",
    vendor: "Ivanti",
    product: "Ivanti Neurons for UEM",
    category: "MDM / UEM",
    signalTypes: ["device-posture"],
    status: "not-configured",
    lastSync: null,
    signalsIngested24h: 0,
    latencyMs: 0,
    description: "AI-powered UEM — self-healing endpoints and automated patch management for enterprise device fleets.",
  },
  {
    id: "maas360",
    vendor: "IBM",
    product: "IBM Security MaaS360",
    category: "MDM / UEM",
    signalTypes: ["device-posture", "identity"],
    status: "not-configured",
    lastSync: null,
    signalsIngested24h: 0,
    latencyMs: 0,
    apiDocsUrl: "https://developer.ibm.com/apis/catalog/maas360--ibm-maas360-apis",
    description: "AI-driven UEM — unified management for endpoints, apps, and content with Watson-powered threat insights.",
  },
  {
    id: "manageengine-uem",
    vendor: "ManageEngine",
    product: "Endpoint Central",
    category: "MDM / UEM",
    signalTypes: ["device-posture"],
    status: "not-configured",
    lastSync: null,
    signalsIngested24h: 0,
    latencyMs: 0,
    description: "Unified endpoint management and security — patch management, OS deployment, and software distribution.",
  },

  // ── EDR / XDR ─────────────────────────────────────────────────────────────
  {
    id: "crowdstrike",
    vendor: "CrowdStrike",
    product: "Falcon Platform",
    category: "EDR / XDR",
    signalTypes: ["device-posture", "operational-signals"],
    status: "connected",
    lastSync: new Date(Date.now() - 4_000).toISOString(),
    signalsIngested24h: 14_892,
    latencyMs: 68,
    apiDocsUrl: "https://developer.crowdstrike.com/crowdstrike/docs",
    description: "Cloud-native EDR/XDR — real-time threat detection, Zero Trust Assessment scores, and device health telemetry via Falcon APIs.",
  },
  {
    id: "sentinelone",
    vendor: "SentinelOne",
    product: "Singularity Platform",
    category: "EDR / XDR",
    signalTypes: ["device-posture", "operational-signals"],
    status: "connected",
    lastSync: new Date(Date.now() - 11_000).toISOString(),
    signalsIngested24h: 9341,
    latencyMs: 84,
    apiDocsUrl: "https://developer.sentinelone.com/",
    description: "AI-powered EDR/XDR — autonomous threat response and device risk scoring integrated with Ranger network discovery.",
  },
  {
    id: "defender",
    vendor: "Microsoft",
    product: "Defender for Endpoint",
    category: "EDR / XDR",
    signalTypes: ["device-posture", "operational-signals"],
    status: "connected",
    lastSync: new Date(Date.now() - 7_000).toISOString(),
    signalsIngested24h: 7234,
    latencyMs: 129,
    description: "Microsoft EDR — device risk scores, security configuration assessment, and threat & vulnerability management via Microsoft Graph Security API.",
  },
  {
    id: "wazuh",
    vendor: "Wazuh",
    product: "Wazuh SIEM + EDR",
    category: "EDR / XDR",
    signalTypes: ["device-posture", "operational-signals"],
    status: "connected",
    lastSync: new Date(Date.now() - 38_000).toISOString(),
    signalsIngested24h: 5102,
    latencyMs: 201,
    githubUrl: "https://github.com/wazuh/wazuh",
    description: "Open-source SIEM/XDR platform — log analysis, intrusion detection, vulnerability detection, and regulatory compliance across hybrid environments.",
  },
  {
    id: "velociraptor",
    vendor: "Rapid7 (OpenSource)",
    product: "Velociraptor",
    category: "EDR / XDR",
    signalTypes: ["device-posture", "operational-signals"],
    status: "connected",
    lastSync: new Date(Date.now() - 62_000).toISOString(),
    signalsIngested24h: 1847,
    latencyMs: 156,
    githubUrl: "https://github.com/Velocidex/velociraptor",
    description: "Advanced digital forensics and incident response platform — real-time endpoint interrogation using VQL (Velociraptor Query Language) for threat hunting at scale.",
  },
  {
    id: "palo-alto-cortex",
    vendor: "Palo Alto Networks",
    product: "Cortex XDR",
    category: "EDR / XDR",
    signalTypes: ["device-posture", "operational-signals"],
    status: "not-configured",
    lastSync: null,
    signalsIngested24h: 0,
    latencyMs: 0,
    githubUrl: "https://github.com/PaloAltoNetworks",
    description: "Extended detection and response — correlates endpoint, network, and cloud data for unified threat analysis.",
  },
  {
    id: "security-onion",
    vendor: "Security Onion Solutions",
    product: "Security Onion",
    category: "EDR / XDR",
    signalTypes: ["network-posture", "operational-signals"],
    status: "not-configured",
    lastSync: null,
    signalsIngested24h: 0,
    latencyMs: 0,
    githubUrl: "https://github.com/Security-Onion-Solutions/securityonion",
    description: "Open-source threat hunting and network security monitoring platform — integrates Zeek, Suricata, Elasticsearch, and Kibana for NSM at scale.",
  },

  // ── SIEM / Log Analytics ──────────────────────────────────────────────────
  {
    id: "splunk",
    vendor: "Splunk",
    product: "Splunk Enterprise Security",
    category: "SIEM",
    signalTypes: ["operational-signals", "identity"],
    status: "connected",
    lastSync: new Date(Date.now() - 16_000).toISOString(),
    signalsIngested24h: 3201,
    latencyMs: 298,
    apiDocsUrl: "https://dev.splunk.com/enterprise/docs/devtools/restapi/",
    description: "SIEM correlation — enriched security events, user behavior analytics, and operational signal aggregation via REST API and Splunk Web Framework.",
  },
  {
    id: "sentinel",
    vendor: "Microsoft",
    product: "Microsoft Sentinel",
    category: "SIEM",
    signalTypes: ["operational-signals", "identity"],
    status: "connected",
    lastSync: new Date(Date.now() - 25_000).toISOString(),
    signalsIngested24h: 2847,
    latencyMs: 341,
    githubUrl: "https://github.com/Azure/Azure-Sentinel",
    description: "Cloud-native SIEM/SOAR — AI-driven threat detection and investigation. 200+ connectors including Cisco, Fortinet, F5, Symantec, and enterprise security integrations.",
  },
  {
    id: "elastic-siem",
    vendor: "Elastic",
    product: "Elastic Security",
    category: "SIEM",
    signalTypes: ["operational-signals", "network-posture"],
    status: "not-configured",
    lastSync: null,
    signalsIngested24h: 0,
    latencyMs: 0,
    githubUrl: "https://github.com/elastic/security-team",
    apiDocsUrl: "https://www.elastic.co/docs/api/doc/elasticsearch/",
    description: "Open-source SIEM on the Elastic Stack — real-time threat detection, ML anomaly detection, and SOAR-style automated response playbooks.",
  },
  {
    id: "thehive",
    vendor: "StrangeBee",
    product: "TheHive",
    category: "SIEM",
    signalTypes: ["operational-signals"],
    status: "not-configured",
    lastSync: null,
    signalsIngested24h: 0,
    latencyMs: 0,
    githubUrl: "https://github.com/TheHive-Project/TheHive",
    description: "Open-source security incident response platform — case management, alert triage, and MISP threat intelligence integration for SOC teams.",
  },

  // ── Networking / SDN ──────────────────────────────────────────────────────
  {
    id: "cisco-meraki",
    vendor: "Cisco",
    product: "Meraki Dashboard",
    category: "Networking / SDN",
    signalTypes: ["network-posture", "device-posture"],
    status: "connected",
    lastSync: new Date(Date.now() - 24_000).toISOString(),
    signalsIngested24h: 6821,
    latencyMs: 143,
    apiDocsUrl: "https://developer.cisco.com/meraki/api-v1/",
    description: "Cloud-managed networking platform — network topology, client device context, SSID/VLAN posture, and rogue device detection via Dashboard API.",
  },
  {
    id: "cisco-ise",
    vendor: "Cisco",
    product: "Cisco ISE",
    category: "Networking / SDN",
    signalTypes: ["network-posture", "identity"],
    status: "connected",
    lastSync: new Date(Date.now() - 19_000).toISOString(),
    signalsIngested24h: 4103,
    latencyMs: 289,
    apiDocsUrl: "https://developer.cisco.com/docs/identity-services-engine/",
    description: "Identity Services Engine — policy enforcement point for network access control. Provides device posture, profiling, and 802.1X authentication signals for Zero Trust.",
  },
  {
    id: "cisco-dnac",
    vendor: "Cisco",
    product: "Cisco Catalyst Center (DNAC)",
    category: "Networking / SDN",
    signalTypes: ["network-posture", "operational-signals"],
    status: "connected",
    lastSync: new Date(Date.now() - 90_000).toISOString(),
    signalsIngested24h: 1204,
    latencyMs: 412,
    apiDocsUrl: "https://developer.cisco.com/docs/dna-center/",
    description: "DNA Center network management — network health, device inventory, and topology signals via Intent API for campus Zero Trust enforcement.",
  },
  {
    id: "arista-cloudvision",
    vendor: "Arista",
    product: "CloudVision",
    category: "Networking / SDN",
    signalTypes: ["network-posture", "operational-signals"],
    status: "not-configured",
    lastSync: null,
    signalsIngested24h: 0,
    latencyMs: 0,
    githubUrl: "https://github.com/aristanetworks",
    apiDocsUrl: "https://aristanetworks.github.io/cloudvision-apis/",
    description: "Network-wide telemetry and operations platform — streaming network state, device health, and traffic analytics via CloudVision APIs and EOS SDK.",
  },
  {
    id: "juniper-mist",
    vendor: "Juniper Networks",
    product: "Mist AI",
    category: "Networking / SDN",
    signalTypes: ["network-posture", "device-posture"],
    status: "not-configured",
    lastSync: null,
    signalsIngested24h: 0,
    latencyMs: 0,
    githubUrl: "https://github.com/Juniper",
    description: "AI-driven wireless and wired networking — client experience telemetry, RF optimization, and network anomaly signals via Mist APIs and PyEZ SDK.",
  },
  {
    id: "aruba-central",
    vendor: "HPE Aruba",
    product: "Aruba Central",
    category: "Networking / SDN",
    signalTypes: ["network-posture", "device-posture"],
    status: "not-configured",
    lastSync: null,
    signalsIngested24h: 0,
    latencyMs: 0,
    apiDocsUrl: "https://developer.arubanetworks.com/",
    description: "Cloud-managed networking platform — WLAN, SD-WAN, and switch management with client visibility and network access control integration.",
  },
  {
    id: "netbox",
    vendor: "NetBox Labs",
    product: "NetBox",
    category: "Networking / SDN",
    signalTypes: ["network-posture", "operational-signals"],
    status: "not-configured",
    lastSync: null,
    signalsIngested24h: 0,
    latencyMs: 0,
    githubUrl: "https://github.com/netbox-community/netbox",
    description: "Open-source network source of truth — DCIM/IPAM with comprehensive REST API and GraphQL. Authoritative device, IP, and circuit inventory for network automation.",
  },

  // ── Firewall / SASE ────────────────────────────────────────────────────────
  {
    id: "palo-alto-panos",
    vendor: "Palo Alto Networks",
    product: "PAN-OS + Prisma Cloud",
    category: "Firewall / SASE",
    signalTypes: ["network-posture", "device-posture"],
    status: "connected",
    lastSync: new Date(Date.now() - 31_000).toISOString(),
    signalsIngested24h: 5823,
    latencyMs: 187,
    githubUrl: "https://github.com/PaloAltoNetworks",
    apiDocsUrl: "https://docs.paloaltonetworks.com/pan-os/11-1/pan-os-panorama-api",
    description: "Next-gen firewall and cloud security — traffic policy context, GlobalProtect VPN posture, and Prisma Cloud workload risk signals via PAN-OS REST API and Python SDK.",
  },
  {
    id: "fortinet",
    vendor: "Fortinet",
    product: "FortiGate + FortiSIEM",
    category: "Firewall / SASE",
    signalTypes: ["network-posture", "operational-signals"],
    status: "connected",
    lastSync: new Date(Date.now() - 43_000).toISOString(),
    signalsIngested24h: 4102,
    latencyMs: 231,
    githubUrl: "https://github.com/fortinet",
    apiDocsUrl: "https://fndn.fortinet.net/index.php?/fortiapi/1-fortios/",
    description: "Fortinet Security Fabric — firewall policy context, FortiSIEM event correlation, and FortiNAC network access control signals via REST API.",
  },
  {
    id: "checkpoint",
    vendor: "Check Point",
    product: "Check Point NGFW",
    category: "Firewall / SASE",
    signalTypes: ["network-posture", "operational-signals"],
    status: "not-configured",
    lastSync: null,
    signalsIngested24h: 0,
    latencyMs: 0,
    githubUrl: "https://github.com/CheckPointSW",
    apiDocsUrl: "https://sc1.checkpoint.com/documents/latest/APIs/",
    description: "Check Point next-gen firewall — SmartConsole Management API for policy context, threat intelligence feeds, and network anomaly signals.",
  },
  {
    id: "cortex-xsoar",
    vendor: "Palo Alto Networks",
    product: "Cortex XSOAR",
    category: "Firewall / SASE",
    signalTypes: ["operational-signals"],
    status: "not-configured",
    lastSync: null,
    signalsIngested24h: 0,
    latencyMs: 0,
    githubUrl: "https://github.com/demisto/content",
    description: "SOAR platform — 900+ integration content packs including Cisco, Fortinet, Splunk, and identity providers for automated incident response playbooks.",
  },
  {
    id: "pfsense",
    vendor: "Netgate",
    product: "pfSense / OPNsense",
    category: "Firewall / SASE",
    signalTypes: ["network-posture"],
    status: "not-configured",
    lastSync: null,
    signalsIngested24h: 0,
    latencyMs: 0,
    githubUrl: "https://github.com/pfsense/pfsense",
    description: "Open-source firewall/router platform — pfSense and OPNsense provide REST API and XMLRPC interfaces for firewall rule context and traffic policy signals.",
  },

  // ── Physical Access (PACS) ─────────────────────────────────────────────────
  {
    id: "hid-global",
    vendor: "HID Global",
    product: "HID Origo + SAFE",
    category: "Physical Access (PACS)",
    signalTypes: ["physical-access"],
    status: "connected",
    lastSync: new Date(Date.now() - 10_000).toISOString(),
    signalsIngested24h: 3402,
    latencyMs: 134,
    apiDocsUrl: "https://developer.hidglobal.com/",
    description: "Access control credential and reader ecosystem — badge-in/badge-out events, door access audit trails, and mobile credential status for physical Zero Trust convergence.",
  },
  {
    id: "lenel-s2",
    vendor: "Carrier",
    product: "LenelS2 OnGuard",
    category: "Physical Access (PACS)",
    signalTypes: ["physical-access"],
    status: "connected",
    lastSync: new Date(Date.now() - 22_000).toISOString(),
    signalsIngested24h: 2103,
    latencyMs: 198,
    apiDocsUrl: "https://www.lenel.com/support/developer-programs",
    description: "Enterprise physical access control system — OnGuard API provides real-time door events, cardholder status, and access group membership for identity convergence.",
  },
  {
    id: "genetec",
    vendor: "Genetec",
    product: "Security Center",
    category: "Physical Access (PACS)",
    signalTypes: ["physical-access"],
    status: "connected",
    lastSync: new Date(Date.now() - 35_000).toISOString(),
    signalsIngested24h: 1841,
    latencyMs: 267,
    apiDocsUrl: "https://genetec.com/resources/developer-zone",
    description: "Unified physical security platform — Security Center SDK provides access control, video surveillance, and ALPR events for unified physical/digital identity posture.",
  },
  {
    id: "gallagher",
    vendor: "Gallagher Security",
    product: "Gallagher Command Centre",
    category: "Physical Access (PACS)",
    signalTypes: ["physical-access"],
    status: "not-configured",
    lastSync: null,
    signalsIngested24h: 0,
    latencyMs: 0,
    apiDocsUrl: "https://gallagher.com/support/developer-tools",
    description: "Enterprise PACS with REST API — access event streaming, cardholder management, and zone occupancy signals for high-security environments.",
  },
  {
    id: "brivo",
    vendor: "Brivo",
    product: "Brivo Access",
    category: "Physical Access (PACS)",
    signalTypes: ["physical-access"],
    status: "not-configured",
    lastSync: null,
    signalsIngested24h: 0,
    latencyMs: 0,
    apiDocsUrl: "https://apidocs.brivo.com/",
    description: "Cloud-based physical access control — Brivo API provides real-time access events, credential management, and video integration for cloud-first deployments.",
  },
  {
    id: "kisi",
    vendor: "Kisi",
    product: "Kisi Access Control",
    category: "Physical Access (PACS)",
    signalTypes: ["physical-access"],
    status: "not-configured",
    lastSync: null,
    signalsIngested24h: 0,
    latencyMs: 0,
    apiDocsUrl: "https://api.kisi.io/docs",
    description: "Modern cloud access control with REST API — mobile credentials, real-time access logs, and lockdown commands for converged physical/digital identity.",
  },

  // ── ITSM ─────────────────────────────────────────────────────────────────
  {
    id: "servicenow",
    vendor: "ServiceNow",
    product: "ServiceNow ITSM",
    category: "ITSM",
    signalTypes: ["operational-signals"],
    status: "connected",
    lastSync: new Date(Date.now() - 90_000).toISOString(),
    signalsIngested24h: 284,
    latencyMs: 423,
    apiDocsUrl: "https://developer.servicenow.com/dev.do#!/reference/api",
    description: "IT service management — open incident context, change windows, CMDB device records, and configuration item status for operational risk assessment.",
  },
  {
    id: "jira",
    vendor: "Atlassian",
    product: "Jira Service Management",
    category: "ITSM",
    signalTypes: ["operational-signals"],
    status: "connected",
    lastSync: new Date(Date.now() - 180_000).toISOString(),
    signalsIngested24h: 121,
    latencyMs: 387,
    description: "ITSM and incident management — open ticket context and escalation signals for operational risk assessment.",
  },
];

router.get("/integrations", (_req, res) => {
  res.json({ integrations: INTEGRATIONS });
});

router.get("/integrations/:id", (req, res) => {
  const parsed = GetIntegrationParams.safeParse(req.params);
  if (!parsed.success) {
    res.status(400).json({ error: "validation", message: "Invalid integration ID" });
    return;
  }

  const integration = INTEGRATIONS.find((i) => i.id === parsed.data.id);
  if (!integration) {
    res.status(404).json({ error: "not_found", message: "Integration not found" });
    return;
  }

  res.json(integration);
});

export default router;
